// swift-tools-version: 5.9
// The swift-tools-version declares the minimum version of Swift required to build this package.

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "Device",
    platforms: [
        .iOS("15.2"),
        .macOS("14.3"),
        .tvOS("15.0"),
        .watchOS("8.0"),
        .visionOS("1.0")
    ],
    products: [
        // Products define the executables and libraries a package produces, and make them visible to other packages.
        .library(
            name: "Device",
            targets: ["Device"]
        ),
        .iOSApplication(
            name: "DeviceTestApp",
            targets: ["DeviceTestAppModule"],
            teamIdentifier: "3QPV894C33",
            displayVersion: "2.0.1",
            bundleVersion: "1",
            appIcon: .asset("AppIcon"),
            accentColor: .presetColor(.blue),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            capabilities: [
                .outgoingNetworkConnections()
            ],
            appCategory: .developerTools
        )
    ],
    targets: [
        // Targets are the basic building blocks of a package. A target can define a module or a test suite.

        // Targets can depend on other targets in this package, and on products in packages this package depends on.
        .target(
            name: "Device",
            path: "Sources"
        ),
        .executableTarget(
            name: "DeviceTestAppModule",
            dependencies: [
                "Device"
            ],
            path: "Development",
            resources: [
                .process("Resources")
            ],
            swiftSettings: [
                .enableUpcomingFeature("BareSlashRegexLiterals")
            ]
        ),
        .testTarget(
            name: "DeviceTests",
            dependencies: [
                "Device"
            ],
            path: "Tests"
        )
    ]
)
