// swift-tools-version: 5.9

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "Device",
    platforms: [
        .iOS("15.2"),
        .macOS("14.3"),
        .tvOS("15.0"),
        .watchOS("8.0"),
        .visionOS("1.0")
    ],
    products: [
        .library(
            name: "Device",
            targets: ["Device"]
        ),
        .iOSApplication(
            name: "DeviceTestApp",
            targets: ["DeviceTestAppModule"],
            teamIdentifier: "3QPV894C33",
            displayVersion: "1.0.8",
            bundleVersion: "1",
            appIcon: .asset("AppIcon"),
            accentColor: .presetColor(.blue),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            capabilities: [
                .outgoingNetworkConnections()
            ],
            appCategory: .developerTools
        )
    ],
    targets: [
        .target(
            name: "Device",
            path: "Sources"
        ),
        .executableTarget(
            name: "DeviceTestAppModule",
            dependencies: [
                "Device"
            ],
            path: "Development",
            resources: [
                .process("Resources")
            ],
            swiftSettings: [
                .enableUpcomingFeature("BareSlashRegexLiterals")
            ]
        ),
        .testTarget(
            name: "DeviceTests",
            dependencies: [
                "Device"
            ],
            path: "Tests"
        )
    ]
)