//
//  iPads.swift
//  Device
//
//  Created by Ben Ku on 4/18/25.
//

import Compatibility

public struct iPad: IdiomType, HasScreen, HasCameras, HasCellular {
    public let device: Device
    public init(knownDevice: Device) {
        self.device = knownDevice
    }

    public init(
        officialName: String,
        identifiers: [String],
        introduction: DateString? = nil,
        supportId: String,
        launchOSVersion: Version,
        unsupportedOSVersion: Version?,
        image: String?,
        capabilities: Capabilities = [],
        models: [String] = [],
        colors: [MaterialColor],
        cpu: CPU,
        cameras: Set<Camera>,
        cellular: Cellular,
        screen: Screen,
        pencils: Set<ApplePencil> = []
    ) {
        var capabilities = capabilities
        capabilities.cameras = cameras
        capabilities.cellular = cellular
        capabilities.screen = screen
        capabilities.pencils = pencils
        device = Device(
            idiom: .pad,
            officialName: officialName,
            identifiers: identifiers,
            introduction: introduction,
            supportId: supportId,
            launchOSVersion: launchOSVersion,
            unsupportedOSVersion: unsupportedOSVersion,
            image: image,
            capabilities: capabilities.union(Device.Idiom.pad.capabilities), // things ALL iPads have
            models: models,
            colors: colors,
            cpu: cpu
        )
    }
    
    init(identifier: String) {
        self.init(
            officialName: "Unknown iPad",
            identifiers: [identifier],
            supportId: .unknownSupportId,
            launchOSVersion: "18",
            unsupportedOSVersion: nil,
            image: nil,
            capabilities: identifier == .base ? [] : [
                // defaults for new unknown devices
                .usbC, .roundedCorners, .biometrics(.faceID),
            ],
            colors: .default,
            cpu: .unknown,
            cameras: [.wide, .trueDepth],
            cellular: identifier == .base ? .none : .fiveG,
            screen: identifier == .base ? .wUnknown : .i129,
            pencils: [.usbC])
    }
    
    /// An SF Symbol name for an icon representing the device.  If no specific variant exists, uses a generic symbol for device idiom.
    public var symbolName: String {
        if #available(iOS 16, macOS 13, macCatalyst 16, tvOS 16, watchOS 9,  *) {
            if biometrics == .faceID {
                return "ipad.gen2"
            } else {
                return "ipad.gen1"
            }
        } else {
            if biometrics == .faceID {
                return "ipad"
            } else {
                return "ipad.homebutton"
            }
        }
    }

    /// Returns whether or not the device is compatible with Apple Pencil
    public var isApplePencilCapable: Bool {
        pencils.count > 0
    }
    
    public var pencils: Set<ApplePencil> {
        return capabilities.pencils
    }

    static let all = [
        
        iPad(
            officialName: "iPad",
            identifiers: ["iPad1,1", "iPad1,2"], // 1,2 is 3g model
            introduction: 2010.introductionYear,
            supportId: "SP580",
            launchOSVersion: "3.2",
            unsupportedOSVersion: "6",
            image: "https://cdsassets.apple.com/live/7WUAS350/images/ipad/ipad/identify-ipad.png",
            capabilities: [.headphoneJack, .thirtyPin, .ringerSwitch],
            models: ["A1219", "A1337"],
            colors: [.silver],
            cpu: .a4,
            cameras: [.iSight],
            cellular: .threeG,
            screen: .i97x768),
        iPad(
            officialName: "iPad 2",
            identifiers: ["iPad2,1", "iPad2,2", "iPad2,3", "iPad2,4"],
            introduction: 2011.introductionYear,
            supportId: "sp622",
            launchOSVersion: "4.3",
            unsupportedOSVersion: "10",
            image: "https://cdsassets.apple.com/live/7WUAS350/images/ipad/ipad/identify-ipad-2gen.png",
            capabilities: [.headphoneJack, .thirtyPin, .ringerSwitch],
            models: ["A1395", "A1396", "A1397"],
            colors: [.white, .black],
            cpu: .a5,
            cameras: [.iSight, .vga],
            cellular: .threeG,
            screen: .i97x768),
        iPad(
            officialName: "iPad (3rd generation)",
            identifiers: ["iPad3,1", "iPad3,2", "iPad3,3"],
            introduction: 2012.introductionYear,
            supportId: "SP647",
            launchOSVersion: "5.1",
            unsupportedOSVersion: "10",
            image: "https://cdsassets.apple.com/live/7WUAS350/images/ipad/ipad/identify-ipad-3gen.png",
            capabilities: [.headphoneJack, .thirtyPin, .ringerSwitch],
            models: ["A1416", "A1430", "A1403"],
            colors: [.white, .black],
            cpu: .a5x,
            cameras: [.iSight, .vga], // 5mpx
            cellular: .lte,
            screen: .i97x1536),
        iPad(
            officialName: "iPad Mini",
            identifiers: ["iPad2,5", "iPad2,6", "iPad2,7"],
            introduction: 2012.introductionYear,
            supportId: "SP661",
            launchOSVersion: "6",
            unsupportedOSVersion: "10",
            image: "https://cdsassets.apple.com/live/7WUAS350/images/ipad/ipad/identify-ipad-mini.png",
            capabilities: [.mini, .headphoneJack, .lightning, .ringerSwitch],
            models: ["A1432", "A1454", "A1455"],
            colors: [.white, .black],
            cpu: .a5,
            cameras: [.iSight, .faceTimeHD720p],
            cellular: .lte,
            screen: .i79x768),
        iPad(
            officialName: "iPad (4th generation)",
            identifiers: ["iPad3,4", "iPad3,5", "iPad3,6"],
            introduction: 2012.introductionYear,
            supportId: "SP662",
            launchOSVersion: "6",
            unsupportedOSVersion: "11",
            image: "https://cdsassets.apple.com/live/7WUAS350/images/ipad/ipad/identify-ipad-4gen.png",
            capabilities: [.headphoneJack, .lightning, .ringerSwitch],
            models: ["A1458", "A1459", "A1460"],
            colors: [.white, .black],
            cpu: .a6x,
            cameras: [.iSight],
            cellular: .lte,
            screen: .i97x1536),
        iPad(
            officialName: "iPad Air",
            identifiers: ["iPad4,1", "iPad4,2", "iPad4,3"],
            introduction: 2013.introductionYear,
            supportId: "SP692",
            launchOSVersion: "7.0.3",
            unsupportedOSVersion: "13",
            image: "https://cdsassets.apple.com/live/7WUAS350/images/ipad/ipad/identify-ipad-air.png",
            capabilities: [.air, .headphoneJack, .lightning, .ringerSwitch],
            models: ["A1474", "A1475", "A1476"],
            colors: .iPadAir,
            cpu: .a7,
            cameras: [.iSight, .faceTimeHD720p],
            cellular: .lte,
            screen: .i97x1536),
        iPad(
            officialName: "iPad Mini 2",
            identifiers: ["iPad4,4", "iPad4,5", "iPad4,6"],
            introduction: 2013.introductionYear,
            supportId: "SP693",
            launchOSVersion: "7.0.3",
            unsupportedOSVersion: "13",
            image: "https://cdsassets.apple.com/live/7WUAS350/images/ipad/ipad/identify-ipad-mini2.png",
            capabilities: [.mini, .headphoneJack, .lightning, .ringerSwitch],
            models: ["A1489", "A1490", "A1491"],
            colors: .iPadAir,
            cpu: .a7,
            cameras: [.iSight, .faceTimeHD720p],
            cellular: .lte,
            screen: .i79x1536),
        iPad(
            officialName: "iPad Mini 3",
            identifiers: ["iPad4,7", "iPad4,8", "iPad4,9"],
            introduction: 2014.introductionYear,
            supportId: "SP709",
            launchOSVersion: "8.1",
            unsupportedOSVersion: "13",
            image: "https://cdsassets.apple.com/live/7WUAS350/images/ipad/ipad/identify-ipad-mini3.png",
            capabilities: [.mini, .headphoneJack, .lightning, .biometrics(.touchID), .ringerSwitch],
            models: ["A1599", "A1600", "A1601"], // A1601 - China-only model
            colors: .iPhone6,
            cpu: .a7,
            cameras: [.iSight, .faceTimeHD720p],
            cellular: .lte,
            screen: .i79x1536),
        iPad(
            officialName: "iPad Mini 4",
            identifiers: ["iPad5,1", "iPad5,2"],
            introduction: 2015.introductionYear,
            supportId: "SP725",
            launchOSVersion: "9",
            unsupportedOSVersion: "16",
            image: "https://cdsassets.apple.com/live/7WUAS350/images/ipad/ipad/identify-ipad-mini4.png",
            capabilities: [.mini, .headphoneJack, .lightning, .biometrics(.touchID)],
            models: ["A1538", "A1550"],
            colors: .iPhone6,
            cpu: .a8,
            cameras: [.iSight, .faceTimeHD720p],
            cellular: .lte,
            screen: .i79x1536),
        iPad(
            officialName: "iPad Air 2",
            identifiers: ["iPad5,3", "iPad5,4"],
            introduction: 2014.introductionYear,
            supportId: "SP708",
            launchOSVersion: "8.1",
            unsupportedOSVersion: "16",
            image: "https://cdsassets.apple.com/live/7WUAS350/images/ipad/ipad/identify-ipad-air2.png",
            capabilities: [.air, .lightning, .biometrics(.touchID)],
            models: ["A1566", "A1567"],
            colors: .iPhone6,
            cpu: .a8x,
            cameras: [.iSight],
            cellular: .lte,
            screen: .i97x1536),
        iPad(
            officialName: "iPad (5th generation)",
            identifiers: ["iPad6,11", "iPad6,12"],
            introduction: 2017.introductionYear,
            supportId: "SP751",
            launchOSVersion: "10.3",
            unsupportedOSVersion: "17",
            image: "https://cdsassets.apple.com/live/7WUAS350/images/ipad/ipad/ios11-ipad-5gen.png",
            capabilities: [.lightning, .biometrics(.touchID)],
            models: ["A1822", "A1823"], // TODO: Figure out why this had to be added manually and didn't parse.
            colors: .iPhone6,
            cpu: .a9,
            cameras: [.iSight],
            cellular: .lte,
            screen: .i97x1536),
        iPad(
            officialName: "iPad Pro (9.7-inch)",
            identifiers: ["iPad6,3", "iPad6,4"],
            introduction: 2016.introductionYear,
            supportId: "SP739",
            launchOSVersion: "9.3",
            unsupportedOSVersion: "17",
            image: "https://cdsassets.apple.com/live/7WUAS350/images/ipad/ipad/identify-ipad-pro-9-7.png",
            capabilities: [.pro, .lightning, .biometrics(.touchID)],
            models: ["A1673", "A1674", "A1675"],
            colors: [.spaceGray6, .silver6, .gold6, .roseGoldA4],
            cpu: .a9x,
            cameras: [.iSight],
            cellular: .lte,
            screen: .i97x1536,
            pencils: [.firstGeneration]),
        iPad(
            officialName: "iPad Pro (12.9-inch)",
            identifiers: ["iPad6,7", "iPad6,8"],
            introduction: 2015.introductionYear,
            supportId: "SP723",
            launchOSVersion: "9.1",
            unsupportedOSVersion: "17",
            image: "https://cdsassets.apple.com/live/7WUAS350/images/ipad/ipad/identify-ipad-pro.png",
            capabilities: [.pro, .lightning, .biometrics(.touchID)],
            models: ["A1584", "A1652"],
            colors: .iPhone6,
            cpu: .a9x,
            cameras: [.iSight],
            cellular: .lte,
            screen: .i129,
            pencils: [.firstGeneration]),
        iPad(
            officialName: "iPad Pro 12.9-inch (2nd generation)",
            identifiers: ["iPad7,1", "iPad7,2"],
            introduction: 2017.introductionYear,
            supportId: "SP761",
            launchOSVersion: "10.3.2",
            unsupportedOSVersion: "18",
            image: "https://cdsassets.apple.com/live/7WUAS350/images/ipad/ipad/ios11-ipad-pro-12-in.png",
            capabilities: [.pro, .lightning, .biometrics(.touchID)],
            models: ["A1670", "A1671", "A1821"],
            colors: .iPhone6,
            cpu: .a10x,
            cameras: [.iSight],
            cellular: .lte,
            screen: .i129,
            pencils: [.firstGeneration]),
        iPad(
            officialName: "iPad Pro (10.5-inch)",
            identifiers: ["iPad7,3", "iPad7,4"],
            introduction: 2017.introductionYear,
            supportId: "SP762",
            launchOSVersion: "10.3.2",
            unsupportedOSVersion: "18",
            image: "https://cdsassets.apple.com/live/7WUAS350/images/ipad/ipad/ios11-ipad-pro-10-in.png",
            capabilities: [.pro, .lightning, .biometrics(.touchID)],
            models: ["A1701", "A1709", "A1852"],
            colors: [.spaceGray6, .silver6, .gold6, .roseGoldSE],
            cpu: .a10x,
            cameras: [.iSight],
            cellular: .lte,
            screen: .i105,
            pencils: [.firstGeneration]),
        iPad(
            officialName: "iPad (6th generation)",
            identifiers: ["iPad7,5", "iPad7,6"],
            introduction: 2018.introductionYear,
            supportId: "SP774",
            launchOSVersion: "11.4",
            unsupportedOSVersion: "18",
            image: "https://cdsassets.apple.com/live/7WUAS350/images/ipad/ipad/ios11-3-ipad-9-7-in-2018.png",
            capabilities: [.lightning, .biometrics(.touchID)],
            models: ["A1893", "A1954"],
            colors: [.spaceGray6, .silver6, .goldM5],
            cpu: .a10,
            cameras: [.iSight],
            cellular: .lte,
            screen: .i97x1536,
            pencils: [.firstGeneration]),
        iPad(
            officialName: "iPad Pro 11-inch",
            identifiers: ["iPad8,1", "iPad8,2", "iPad8,3", "iPad8,4"],
            introduction: 2018.introductionYear,
            supportId: "SP784",
            launchOSVersion: "12.1",
            unsupportedOSVersion: nil,
            image: "https://cdsassets.apple.com/live/7WUAS350/images/ipad/ipad/ios12-ipad-pro-11-in.png",
            capabilities: [.pro, .usbC, .biometrics(.faceID), .esim, .roundedCorners, .notch],
            models: ["A1980", "A2013", "A1934", "A1979"],
            colors: [.spaceGrayM5, .silver6],
            cpu: .a12x,
            cameras: [.iSight],
            cellular: .lte,
            screen: .i11,
            pencils: [.secondGeneration, .usbC]),
        iPad(
            officialName: "iPad Pro 12.9-inch (3rd generation)",
            identifiers: ["iPad8,5", "iPad8,6", "iPad8,7", "iPad8,8"],
            introduction: 2018.introductionYear,
            supportId: "SP785",
            launchOSVersion: "12.1",
            unsupportedOSVersion: nil,
            image: "https://cdsassets.apple.com/live/7WUAS350/images/ipad/ipad/ios12-ipad-pro-12-9-in.png",
            capabilities: [.pro, .usbC, .biometrics(.faceID), .esim, .roundedCorners, .notch, .barometer],
            models: ["A1876", "A2014", "A1895", "A1983"],
            colors: [.spaceGrayM5, .silver6],
            cpu: .a12x,
            cameras: [.iSight],
            cellular: .lte,
            screen: .i129,
            pencils: [.secondGeneration, .usbC]),
        iPad(
            officialName: "iPad Air (3rd generation)",
            identifiers: ["iPad11,3", "iPad11,4"],
            introduction: 2019.introductionYear,
            supportId: "SP787",
            launchOSVersion: "12.2",
            unsupportedOSVersion: nil,
            image: "https://cdsassets.apple.com/live/7WUAS350/images/ipad/ipad/ipad-air-3gen.png",
            capabilities: [.air, .lightning, .biometrics(.touchID), .esim],
            models: ["A2152", "A2123", "A2153", "A2154"],
            colors: .iPadMini5,
            cpu: .a12,
            cameras: [.iSight],
            cellular: .lte,
            screen: .i105,
            pencils: [.firstGeneration]),
        iPad(
            officialName: "iPad Mini (5th generation)",
            identifiers: ["iPad11,1", "iPad11,2"],
            introduction: 2019.introductionYear,
            supportId: "SP788",
            launchOSVersion: "12.2",
            unsupportedOSVersion: nil,
            image: "https://cdsassets.apple.com/live/7WUAS350/images/ipad/ipad/ipad-mini-5gen.png",
            capabilities: [.mini, .headphoneJack, .lightning, .biometrics(.touchID), .esim],
            models: ["A2133", "A2124", "A2125", "A2126"],
            colors: .iPadMini5,
            cpu: .a12,
            cameras: [.iSight, .faceTimeHD1080p],
            cellular: .lte,
            screen: .i79x1536,
            pencils: [.firstGeneration]),
        iPad(
            officialName: "iPad (7th generation)",
            identifiers: ["iPad7,11", "iPad7,12"],
            introduction: 2019.introductionYear,
            supportId: "SP807",
            launchOSVersion: "13.1",
            unsupportedOSVersion: nil,
            image: "https://cdsassets.apple.com/live/7WUAS350/images/ipad/ipad/ipad-7th-gen.png",
            capabilities: [.lightning, .biometrics(.touchID), .esim],
            models: ["A2197", "A2200", "A2198"],
            colors: .iPadMini5,
            cpu: .a10,
            cameras: [.iSight],
            cellular: .lte,
            screen: .i102,
            pencils: [.firstGeneration]),
        iPad(
            officialName: "iPad Pro 11-inch (2nd generation)",
            identifiers: ["iPad8,9", "iPad8,10"],
            introduction: 2020.introductionYear,
            supportId: "SP814",
            launchOSVersion: "13.4",
            unsupportedOSVersion: nil,
            image: "https://cdsassets.apple.com/live/7WUAS350/images/ipad/ipad/ios13-4-ipad-pro-4gen-11-in.png",
            capabilities: [.pro, .usbC, .biometrics(.faceID), .esim, .roundedCorners, .notch, .lidar, .barometer],
            models: ["A2228", "A2068", "A2230", "A2231"],
            colors: [.spaceGrayM5, .silver6],
            cpu: .a12z,
            cameras: [.iSight, .wide, .ultraWide, .trueDepth],
            cellular: .lte,
            screen: .i11,
            pencils: [.secondGeneration, .usbC]),
        iPad(
            officialName: "iPad Pro 12.9-inch (4th generation)",
            identifiers: ["iPad8,11", "iPad8,12"],
            introduction: 2020.introductionYear,
            supportId: "SP815",
            launchOSVersion: "13.4",
            unsupportedOSVersion: nil,
            image: "https://cdsassets.apple.com/live/7WUAS350/images/ipad/ipad/ios13-4-ipad-pro-4gen-12-9-in.png",
            capabilities: [.pro, .usbC, .biometrics(.faceID), .esim, .roundedCorners, .notch, .lidar, .barometer],
            models: ["A2229", "A2069", "A2232", "A2233"],
            colors: [.spaceGrayM5, .silver6],
            cpu: .a12z,
            cameras: [.iSight, .wide, .ultraWide, .trueDepth],
            cellular: .lte,
            screen: .i129,
            pencils: [.secondGeneration, .usbC]),
        iPad(
            officialName: "iPad (8th generation)",
            identifiers: ["iPad11,6", "iPad11,7"],
            introduction: 2020.introductionYear,
            supportId: "SP822",
            launchOSVersion: "14",
            unsupportedOSVersion: nil,
            image: "https://cdsassets.apple.com/live/7WUAS350/images/ipad/ipad/ipad-8th-gen-colors.png",
            capabilities: [.lightning, .biometrics(.touchID), .esim],
            models: ["A2270", "A2428", "A2429", "A2430"],
            colors: .iPadMini5,
            cpu: .a12,
            cameras: [.iSight],
            cellular: .lte,
            screen: .i102,
            pencils: [.firstGeneration]),
        iPad(
            officialName: "iPad (9th generation)",
            identifiers: ["iPad12,1", "iPad12,2"],
            introduction: 2021.introductionYear,
            supportId: "SP849",
            launchOSVersion: "15",
            unsupportedOSVersion: nil,
            image: "https://cdsassets.apple.com/live/7WUAS350/images/ipad/ipad/ipad-2021-colors.png",
            capabilities: [.lightning, .biometrics(.touchID), .esim],
            models: ["A2602", "A2604", "A2603", "A2605"],
            colors: [.spaceGray9, .silver6],
            cpu: .a13,
            cameras: [.iSight],
            cellular: .lte,
            screen: .i102,
            pencils: [.firstGeneration]),
        iPad(
            officialName: "iPad Air (4th generation)",
            identifiers: ["iPad13,1", "iPad13,2"],
            introduction: 2020.introductionYear,
            supportId: "SP828",
            launchOSVersion: "14.1",
            unsupportedOSVersion: nil,
            image: "https://cdsassets.apple.com/live/7WUAS350/images/ipad/ipad/ipad-air-4th-gen-colors.png",
            capabilities: [.air, .usbC, .biometrics(.touchID), .esim, .roundedCorners, .barometer],
            models: ["A2316", "A2324", "A2325", "A2072"],
            colors: [.spaceGrayM5, .silver6, .roseGoldA4, .skyBlueA4, .greenA4],
            cpu: .a14,
            cameras: [.iSight, .wide, .faceTimeHD1080p],
            cellular: .lte,
            screen: .i109,
            pencils: [.secondGeneration, .usbC]),
        iPad(
            officialName: "iPad Air (5th generation)",
            identifiers: ["iPad13,16", "iPad13,17"],
            introduction: 2022.introductionYear,
            supportId: "SP866",
            launchOSVersion: "15.4",
            unsupportedOSVersion: nil,
            image: "https://cdsassets.apple.com/live/7WUAS350/images/ipad/ipad-air-5th-gen-colors.png",
            capabilities: [.air, .usbC, .biometrics(.touchID), .esim, .roundedCorners, .barometer, .appleIntelligence],
            models: ["A2588", "A2589", "A2591"],
            colors: [.spaceGrayA5, .starlightA5, .pinkA5, .purpleA5, .blueA5],
            cpu: .m1,
            cameras: [.iSight, .wide, .faceTimeHD1080p],
            cellular: .fiveG,
            screen: .i109,
            pencils: [.secondGeneration, .usbC]),
        iPad(
            officialName: "iPad (10th generation)",
            identifiers: ["iPad13,18", "iPad13,19"],
            introduction: 2022.introductionYear,
            supportId: "SP884",
            launchOSVersion: "16.1",
            unsupportedOSVersion: nil,
            image: "https://cdsassets.apple.com/live/7WUAS350/images/ipad/ipad/fall-2022-10-gen-ipad.png",
            capabilities: [.usbC, .biometrics(.touchID), .esim, .roundedCorners],
            models: ["A2696", "A2757", "A2777", "A3162"],
            colors: .iPad10,
            cpu: .a14,
            cameras: [.iSight],
            cellular: .fiveG,
            screen: .i109,
            pencils: [.firstGeneration, .usbC]),
        iPad(
            officialName: "iPad Pro 11-inch (3rd generation)",
            identifiers: ["iPad13,4", "iPad13,5", "iPad13,6", "iPad13,7"],
            introduction: 2021.introductionYear,
            supportId: "SP843",
            launchOSVersion: "14.5.1",
            unsupportedOSVersion: nil,
            image: "https://cdsassets.apple.com/live/7WUAS350/images/ipad/ipad/2021-ipad-pro-11-colors.png",
            capabilities: [.pro, .usbC, .thunderbolt, .biometrics(.faceID), .esim, .roundedCorners, .notch, .lidar, .barometer, .appleIntelligence],
            models: ["A2377", "A2459", "A2301", "A2460"],
            colors: [.spaceGrayM5, .silver6],
            cpu: .m1,
            cameras: [.iSight, .wide, .ultraWide, .trueDepth],
            cellular: .fiveG,
            screen: .i11,
            pencils: [.secondGeneration, .usbC]),
        iPad(
            officialName: "iPad Pro 12.9-inch (5th generation)",
            identifiers: ["iPad13,8", "iPad13,9", "iPad13,10", "iPad13,11"],
            introduction: 2021.introductionYear,
            supportId: "SP844",
            launchOSVersion: "14.5.1",
            unsupportedOSVersion: nil,
            image: "https://cdsassets.apple.com/live/7WUAS350/images/ipad/ipad/2021-ipad-pro-12-9-colors.png",
            capabilities: [.pro, .usbC, .thunderbolt, .biometrics(.faceID), .esim, .roundedCorners, .notch, .lidar, .barometer, .appleIntelligence],
            models: ["A2378", "A2379", "A2461", "A2462"],
            colors: [.spaceGrayM5, .silver6],
            cpu: .m1,
            cameras: [.iSight, .wide, .ultraWide, .trueDepth],
            cellular: .fiveG,
            screen: .i129,
            pencils: [.secondGeneration, .usbC]),
        iPad(
            officialName: "iPad Mini (6th generation)",
            identifiers: ["iPad14,1", "iPad14,2"],
            introduction: 2021.introductionYear,
            supportId: "SP850",
            launchOSVersion: "15",
            unsupportedOSVersion: nil,
            image: "https://cdsassets.apple.com/live/7WUAS350/images/ipad/ipad/ipad-mini-2021-colors.png",
            capabilities: [.mini, .usbC, .biometrics(.touchID), .esim, .roundedCorners],
            models: ["A2567", "A2568", "A2569"],
            colors: [.spaceGrayA5, .starlightA5, .pinkA5, .purpleA5],
            cpu: .a15,
            cameras: [.iSight, .wide, .faceTimeHD1080p],
            cellular: .fiveG,
            screen: .i83,
            pencils: [.secondGeneration, .usbC]),
        iPad(
            officialName: "iPad Pro 11-inch (4th generation)",
            identifiers: ["iPad14,3", "iPad14,4"],
            introduction: 2022.introductionYear,
            supportId: "SP882",
            launchOSVersion: "16.1",
            unsupportedOSVersion: nil,
            image: "https://cdsassets.apple.com/live/7WUAS350/images/ipad/ipad/fall-2022-11-inch-4gen-ipad-pro.png",
            capabilities: [.pro, .usbC, .thunderbolt, .biometrics(.faceID), .esim, .roundedCorners, .notch, .lidar, .barometer, .appleIntelligence],
            models: ["A2759", "A2761", "A2435", "A2762"],
            colors: [.spaceGrayM5, .silver6],
            cpu: .m2,
            cameras: [.iSight, .wide, .ultraWide, .trueDepth],
            cellular: .fiveG,
            screen: .i11,
            pencils: [.secondGeneration, .usbC]),
        iPad(
            officialName: "iPad Pro 12.9-inch (6th generation)",
            identifiers: ["iPad14,5", "iPad14,6"],
            introduction: 2022.introductionYear,
            supportId: "SP883",
            launchOSVersion: "16.1",
            unsupportedOSVersion: nil,
            image: "https://cdsassets.apple.com/live/7WUAS350/images/ipad/ipad/fall-2022-12-9-inch-6gen-ipad-pro.png",
            capabilities: [.pro, .usbC, .thunderbolt, .biometrics(.faceID), .esim, .roundedCorners, .notch, .lidar, .barometer, .appleIntelligence],
            models: ["A2436", "A2437", "A2764", "A2766"],
            colors: [.spaceGrayM5, .silver6],
            cpu: .m2,
            cameras: [.iSight, .wide, .ultraWide, .trueDepth],
            cellular: .fiveG,
            screen: .i129,
            pencils: [.secondGeneration, .usbC]),

        // 2024 Spring models
        iPad(
            officialName: "iPad Air 11-inch (M2)",
            identifiers: ["iPad14,8", "iPad14,9"],
            introduction: 2024.introductionYear,
            supportId: "119894",
            launchOSVersion: "17.5",
            unsupportedOSVersion: nil,
            image: "https://cdsassets.apple.com/live/7WUAS350/images/ipad/spring-2024-4.png",
            capabilities: [.air, .usbC, .biometrics(.touchID), .esim, .roundedCorners, .barometer, .appleIntelligence],
            models: ["A2902", "A2903", "A2904"],
            colors: .iPadAirM2,
            cpu: .m2,
            cameras: [.wide, .faceTimeHD1080p],
            cellular: .fiveG,
            screen: .i109,
            pencils: [.usbC, .pro]),
        iPad(
            officialName: "iPad Air 13-inch (M2)",
            identifiers: ["iPad14,10", "iPad14,11"],
            introduction: 2024.introductionYear,
            supportId: "119893",
            launchOSVersion: "17.5",
            unsupportedOSVersion: nil,
            image: "https://cdsassets.apple.com/live/7WUAS350/images/ipad/spring-2024-3.png",
            capabilities: [.air, .usbC, .biometrics(.touchID), .esim, .roundedCorners, .barometer, .appleIntelligence],
            models: ["A2898", "A2899", "A2900"],
            colors: .iPadAirM2,
            cpu: .m2,
            cameras: [.wide, .faceTimeHD1080p],
            cellular: .fiveG,
            screen: .i129,
            pencils: [.usbC, .pro]),
        iPad(
            officialName: "iPad Pro 11-inch (M4)",
            identifiers: ["iPad16,3", "iPad16,4"],
            introduction: 2024.introductionYear,
            supportId: "119892",
            launchOSVersion: "17.5",
            unsupportedOSVersion: nil,
            image: "https://cdsassets.apple.com/live/7WUAS350/images/ipad/spring-2024-2.png",
            capabilities: [.pro, .usbC, .thunderbolt, .biometrics(.faceID), .esim, .roundedCorners, .notch, .lidar, .barometer, .appleIntelligence],
            models: ["A2836", "A2837", "A3006"],
            colors: [.macbookSpaceblack, .solidSilver],
            cpu: .m4,
            cameras: [.wide, .trueDepth],
            cellular: .fiveG,
            screen: .i11,
            pencils: [.usbC, .pro]),
        iPad(
            officialName: "iPad Pro 13-inch (M4)",
            identifiers: ["iPad16,5", "iPad16,6"],
            introduction: 2024.introductionYear,
            supportId: "119891",
            launchOSVersion: "17.5",
            unsupportedOSVersion: nil,
            image: "https://cdsassets.apple.com/live/7WUAS350/images/ipad/spring-2024-1.png",
            capabilities: [.pro, .usbC, .thunderbolt, .biometrics(.faceID), .esim, .roundedCorners, .notch, .lidar, .barometer, .appleIntelligence],
            models: ["A2925", "A2926", "A3007"],
            colors: [.macbookSpaceblack, .solidSilver],
            cpu: .m4,
            cameras: [.wide, .trueDepth],
            cellular: .fiveG,
            screen: .i13,
            pencils: [.usbC, .pro]),
        iPad(
            officialName: "iPad mini (A17 Pro)",
            identifiers: ["iPad16,1", "iPad16,2"],
            introduction: 2024.introductionYear,
            supportId: "121456",
            launchOSVersion: "18", // iPadOS 18 (22A8350)
            unsupportedOSVersion: nil,
            image: "https://cdsassets.apple.com/live/7WUAS350/images/ipad/ipad-mini/ipad-mini-2024-colors.png",
            capabilities: [.mini, .usbC, .biometrics(.touchID), .esim, .roundedCorners, .appleIntelligence],
            models: ["A2993", "A2995", "A2996"],
            colors: .iPadAirM2,
            cpu: .a17pro,
            cameras: [.iSight, .wide, .faceTimeHD1080p],
            cellular: .fiveG,
            screen: .i83,
            pencils: [.usbC, .pro]),
        iPad(
            officialName: "iPad Air 13-inch (M3)",
            identifiers: ["iPad15,5", "iPad15,6"],
            introduction: 2025.introductionYear,
            supportId: "122242",
            launchOSVersion: "18.3",
            unsupportedOSVersion: nil,
            image: "https://cdsassets.apple.com/live/7WUAS350/images/ipad/spring-2025-ipad-air-13.png",
            capabilities: [.air, .usbC, .biometrics(.touchID), .esim, .roundedCorners, .barometer, .appleIntelligence],
            models: ["A3268", "A3269", "A3271"],
            colors: .iPadAirM2,
            cpu: .m3,
            cameras: [.wide, .faceTimeHD1080p],
            cellular: .fiveG,
            screen: .i129,
            pencils: [.usbC, .pro]),
        iPad(
            officialName: "iPad Air 11-inch (M3)",
            identifiers: ["iPad15,3", "iPad15,4"],
            introduction: 2025.introductionYear,
            supportId: "122241",
            launchOSVersion: "18.2.1",
            unsupportedOSVersion: nil,
            image: "https://cdsassets.apple.com/live/7WUAS350/images/ipad/spring-2025-ipad-air-11.png",
            capabilities: [.air, .usbC, .biometrics(.touchID), .esim, .roundedCorners, .barometer, .appleIntelligence],
            models: ["A3266", "A3267", "A3270"],
            colors: .iPadAirM2,
            cpu: .m3,
            cameras: [.wide, .faceTimeHD1080p],
            cellular: .fiveG,
            screen: .i109,
            pencils: [.usbC, .pro]),
        iPad(
            officialName: "iPad (A16)",
            identifiers: ["iPad15,7", "iPad15,8"],
            introduction: 2025.introductionYear,
            supportId: "122240",
            launchOSVersion: "18.2.1",
            unsupportedOSVersion: nil,
            image: "https://cdsassets.apple.com/live/7WUAS350/images/ipad/spring-2025-ipad.png",
            capabilities: [.usbC, .biometrics(.touchID), .esim, .roundedCorners, .barometer],
            models: ["A3354", "A3355", "A3356"],
            colors: .iPad10,
            cpu: .a16,
            cameras: [.wide, .faceTimeHD1080p],
            cellular: .fiveG,
            screen: .i109,
            pencils: [.firstGeneration, .usbC]),
    ]
}
