//
//  iPhones.swift
//  Device
//
//  Created by Ben Ku on 4/18/25.
//

import Compatibility

public struct iPhone: IdiomType, HasScreen, HasCameras, HasCellular {
    public let device: Device
    public init(knownDevice: Device) {
        self.device = knownDevice
    }

    public init(
        officialName: String,
        identifiers: [String],
        introduction: DateString? = nil,
        supportId: String,
        launchOSVersion: Version,
        unsupportedOSVersion: Version?,
        image: String?,
        capabilities: Capabilities = [],
        models: [String] = [],
        colors: [MaterialColor],
        cpu: CPU,
        cameras: Set<Camera>, // force setting here
        cellular: Cellular, // force setting here
        screen: Screen // force setting here
    ) {
        var capabilities = capabilities
        capabilities.cameras = cameras
        capabilities.cellular = cellular
        capabilities.screen = screen
        device = Device(
            idiom: .phone,
            officialName: officialName,
            identifiers: identifiers,
            introduction: introduction,
            supportId: supportId,
            launchOSVersion: launchOSVersion,
            unsupportedOSVersion: unsupportedOSVersion,
            image: image,
            capabilities: capabilities.union(Device.Idiom.phone.capabilities), // all iPhones have batteries
            models: models,
            colors: colors,
            cpu: cpu
        )
    }
    
    public init(identifier: String) { // Public for DeviceKit testing
        self.init(
            officialName: "Unknown iPhone",
            identifiers:[identifier],
            supportId: .unknownSupportId,
            launchOSVersion: "18",
            unsupportedOSVersion: nil,
            image: nil,
            // Assume these capabilities of phones going forward minimum.  Don't include if we're wanting the default set not the one going forward
            capabilities: identifier == .base ? [] : [
                // defaults for new unknown devices
                .wirelessCharging, .magSafe, .roundedCorners, .applePay, .barometer, .nfc, .crashDetection,
                .usbC,
                .biometrics(.faceID),
                .dynamicIsland],
            colors: .default,
            cpu: .unknown,
            cameras: .default, // TODO: Make sure this doesn't cause the base to remove during migration
            cellular: identifier == .base ? .none : .fiveG,
            screen: identifier == .base ? .wUnknown : .i61x828
        )
    }

    /// An SF Symbol name for an icon representing the device.  If no specific variant exists, uses a generic symbol for device idiom.
    public var symbolName: String {
        if #available(iOS 16, macOS 13, macCatalyst 16, tvOS 16, watchOS 9,  *) {
            if has(.dynamicIsland) {
                return "iphone.gen3"
            } else if biometrics == .faceID {
                return "iphone.gen2"
            } else {
                return "iphone.gen1"
            }
        } else {
            if !has(.notch) && !has(.dynamicIsland) {
                return "iphone.homebutton"
            } else {
                return "iphone"
            }
        }
    }
    
    public static let all = [ // Public for DeviceKit testing

        iPhone(
            officialName: "iPhone",
            identifiers: ["iPhone1,1"],
            introduction: 2007.introductionYear,
            supportId: "SP2",
            launchOSVersion: "1",
            unsupportedOSVersion: "4",
            image: "https://cdsassets.apple.com/live/7WUAS350/images/iphone/iphone-iphone-original-colors.jpg",
            capabilities: [.headphoneJack, .thirtyPin, .ringerSwitch],
            models: ["A1203"],
            colors: [.silver],
            cpu: .s5L8900,
            cameras: [.twoMP],
            cellular: .edge,
            screen: .i35),
        iPhone(
            officialName: "iPhone 3G",
            identifiers: ["iPhone1,2"],
            introduction: "June 9, 2008", // TODO: Check
            supportId: "SP495",
            launchOSVersion: "2",
            unsupportedOSVersion: "5",
            image: "https://cdsassets.apple.com/live/7WUAS350/images/iphone/iphone-iphone3g-colors.jpg",
            capabilities: [.headphoneJack, .thirtyPin, .ringerSwitch],
            models: ["A1324", "A1241"],
            colors: [.black],
            cpu: .s5L8900,
            cameras: [.twoMP],
            cellular: .threeG,
            screen: .i35),
        iPhone(
            officialName: "iPhone 3GS",
            identifiers: ["iPhone2,1"],
            introduction: 2009.introductionYear,
            supportId: "SP565",
            launchOSVersion: "3",
            unsupportedOSVersion: "7",
            image: "https://cdsassets.apple.com/live/7WUAS350/images/iphone/iphone-iphone3gs-colors.jpg",
            capabilities: [.headphoneJack, .thirtyPin, .ringerSwitch],
            models: ["A1325", "A1303"],
            colors: .iPhoneBW,
            cpu: .s5L8920,
            cameras: [.threeMP],
            cellular: .threeG,
            screen: .i35),

        iPhone(
            officialName: "iPhone 4",
            identifiers: ["iPhone3,1", "iPhone3,2", "iPhone3,3"],
            introduction: 2010.introductionYear,
            supportId: "SP587",
            launchOSVersion: "4",
            unsupportedOSVersion: "8",
            image: "https://cdsassets.apple.com/live/7WUAS350/images/iphone/iphone-iphone4-colors.jpg",
            capabilities: [.headphoneJack, .thirtyPin, .ringerSwitch],
            models: ["A1349", "A1332"],
            colors: .iPhoneBW,
            cpu: .a4,
            cameras: [.iSight, .faceTimeHD720p],
            cellular: .threeG,
            screen: .i35),
        iPhone(
            officialName: "iPhone 4s",
            identifiers: ["iPhone4,1"],
            introduction: 2011.introductionYear,
            supportId: "SP643",
            launchOSVersion: "5",
            unsupportedOSVersion: "10",
            image: "https://cdsassets.apple.com/live/7WUAS350/images/iphone/iphone-iphone4s-colors.jpg",
            capabilities: [.headphoneJack, .thirtyPin, .ringerSwitch],
            models: ["A1431", "A1387"],
            colors: .iPhoneBW,
            cpu: .a5,
            cameras: [.iSight, .faceTimeHD720p],
            cellular: .threeG,
            screen: .i35),
        iPhone(
            officialName: "iPhone 5",
            identifiers: ["iPhone5,1", "iPhone5,2"],
            introduction: 2012.introductionYear,
            supportId: "SP655",
            launchOSVersion: "6",
            unsupportedOSVersion: "11",
            image: "https://cdsassets.apple.com/live/7WUAS350/images/iphone/iphone-iphone5-colors.jpg",
            capabilities: [.headphoneJack, .lightning, .ringerSwitch],
            models: ["A1428", "A1429", "A1442"],
            colors: .iPhoneBW,
            cpu: .a6,
            cameras: [.iSight, .faceTimeHD720p],
            cellular: .lte,
            screen: .i4),
        iPhone(
            officialName: "iPhone 5c",
            identifiers: ["iPhone5,3", "iPhone5,4"],
            introduction: 2013.introductionYear,
            supportId: "SP684",
            launchOSVersion: "7",
            unsupportedOSVersion: "11",
            image: "https://cdsassets.apple.com/live/7WUAS350/images/iphone/iphone-iphone5c-colors.jpg",
            capabilities: [.headphoneJack, .lightning, .ringerSwitch],
            models: ["A1456", "A1507", "A1516", "A1526", "A1529", "A1532"],
            colors: .iPhone5c,
            cpu: .a6,
            cameras: [.iSight, .faceTimeHD720p],
            cellular: .lte,
            screen: .i4),
        iPhone(
            officialName: "iPhone 5s",
            identifiers: ["iPhone6,1", "iPhone6,2"],
            introduction: 2013.introductionYear,
            supportId: "SP685",
            launchOSVersion: "7",
            unsupportedOSVersion: "13",
            image: "https://cdsassets.apple.com/live/7WUAS350/images/iphone/iphone-iphone5s-colors.jpg",
            capabilities: [.headphoneJack, .lightning, .biometrics(.touchID), .ringerSwitch],
            models: ["A1453", "A1457", "A1518", "A1528", "A1530", "A1533"],
            colors: .iPhone6,
            cpu: .a7,
            cameras: [.iSight, .faceTimeHD720p],
            cellular: .lte,
            screen: .i4),
        iPhone(
            officialName: "iPhone 6",
            identifiers: ["iPhone7,2"],
            introduction: 2014.introductionYear,
            supportId: "SP705",
            launchOSVersion: "8",
            unsupportedOSVersion: "13",
            image: "https://cdsassets.apple.com/live/7WUAS350/images/iphone/iphone-iphone6-colors.jpg",
            capabilities: [.headphoneJack, .lightning, .biometrics(.touchID), .ringerSwitch, .barometer, .applePay],
            models: ["A1549", "A1586", "A1589"],
            colors: .iPhone6,
            cpu: .a8,
            cameras: [.iSight, .faceTimeHD720p],
            cellular: .lte,
            screen: .i47),
        iPhone(
            officialName: "iPhone 6 Plus",
            identifiers: ["iPhone7,1"],
            introduction: "2014-09-09",
            supportId: "SP706",
            launchOSVersion: "8",
            unsupportedOSVersion: "13",
            image: "https://cdsassets.apple.com/live/7WUAS350/images/iphone/iphone-iphone6plus-colors.jpg",
            capabilities: [.plus, .headphoneJack, .lightning, .biometrics(.touchID), .ringerSwitch, .barometer, .applePay],
            models: ["A1522", "A1524", "A1593"],
            colors: .iPhone6,
            cpu: .a8,
            cameras: [.iSight, .faceTimeHD720p],
            cellular: .lte,
            screen: .i55),
        iPhone(
            officialName: "iPhone 6s",
            identifiers: ["iPhone8,1"],
            introduction: 2015.introductionYear,
            supportId: "SP726",
            launchOSVersion: "9.0.1",
            unsupportedOSVersion: "16",
            image: "https://cdsassets.apple.com/live/7WUAS350/images/iphone/iphone-6s-colors.jpg",
            capabilities: [.headphoneJack, .lightning, .biometrics(.touchID), .force3DTouch, .ringerSwitch, .barometer, .applePay],
            models: ["A1633", "A1688", "A1691", "A1700"],
            colors: .iPhone6s,
            cpu: .a9,
            cameras: [.iSight, .faceTimeHD720p],
            cellular: .lte,
            screen: .i47),
        iPhone(
            officialName: "iPhone 6s Plus",
            identifiers: ["iPhone8,2"],
            introduction: 2015.introductionYear,
            supportId: "SP727",
            launchOSVersion: "9.0.1",
            unsupportedOSVersion: "16",
            image: "https://cdsassets.apple.com/live/7WUAS350/images/iphone/iphone-6splus-colors.jpg",
            capabilities: [.plus, .headphoneJack, .lightning, .biometrics(.touchID), .force3DTouch, .ringerSwitch, .barometer, .applePay],
            models: ["A1634", "A1687", "A1690", "A1699"],
            colors: .iPhone6s,
            cpu: .a9,
            cameras: [.iSight, .faceTimeHD720p],
            cellular: .lte,
            screen: .i55),
        iPhone(
            officialName: "iPhone SE (1st generation)",
            identifiers: ["iPhone8,4"],
            introduction: 2016.introductionYear,
            supportId: "SP738",
            launchOSVersion: "9.3",
            unsupportedOSVersion: "16",
            image: "https://cdsassets.apple.com/live/7WUAS350/images/iphone/iphone-se/iphone-se-colors.jpg",
            capabilities: [.headphoneJack, .lightning, .biometrics(.touchID), .ringerSwitch, .applePay],
            models: ["A1723", "A1662", "A1724"],
            colors: .iPhoneSE,
            cpu: .a9,
            cameras: [.iSight, .faceTimeHD720p],
            cellular: .lte,
            screen: .i4),
        iPhone(
            officialName: "iPhone 7",
            identifiers: ["iPhone9,1", "iPhone9,3"],
            introduction: 2016.introductionYear,
            supportId: "SP743",
            launchOSVersion: "10",
            unsupportedOSVersion: "16",
            image: "https://cdsassets.apple.com/live/7WUAS350/images/iphone/iphone-7/iphone7-colors.jpg",
            capabilities: [.lightning, .biometrics(.touchID), .nfc, .force3DTouch, .ringerSwitch, .barometer, .applePay],
            models: ["A1660", "A1778", "A1779", "A1780"],
            colors: .iPhone7,
            cpu: .a10,
            cameras: [.main12MP, .faceTimeHD1080p],
            cellular: .lte,
            screen: .i47),
        iPhone(
            officialName: "iPhone 7 Plus",
            identifiers: ["iPhone9,2", "iPhone9,4"],
            introduction: 2016.introductionYear,
            supportId: "SP744",
            launchOSVersion: "10",
            unsupportedOSVersion: "16",
            image: "https://cdsassets.apple.com/live/7WUAS350/images/iphone/iphone-7-plus/iphone7plus-colors.jpg",
            capabilities: [.plus, .lightning, .biometrics(.touchID), .nfc, .force3DTouch, .ringerSwitch, .barometer, .applePay],
            models: ["A1661", "A1784", "A1785", "A1786"],
            colors: .iPhone7,
            cpu: .a10,
            cameras: [.main12MP, .telephoto, .faceTimeHD1080p],
            cellular: .lte,
            screen: .i55),
        iPhone(
            officialName: "iPhone 8",
            identifiers: ["iPhone10,1", "iPhone10,4"],
            introduction: 2017.introductionYear,
            supportId: "SP767",
            launchOSVersion: "11",
            unsupportedOSVersion: "17",
            image: "https://cdsassets.apple.com/live/7WUAS350/images/iphone/iphone-8/iphone-8-colors.jpg",
            capabilities: [.lightning, .wirelessCharging, .biometrics(.touchID), .nfc, .force3DTouch, .ringerSwitch, .barometer, .applePay],
            models: ["A1863", "A1905", "A1906", "A1907"],
            colors: .iPhone8,
            cpu: .a11,
            cameras: [.main12MP, .faceTimeHD1080p],
            cellular: .lte,
            screen: .i47),
        iPhone(
            officialName: "iPhone 8 Plus",
            identifiers: ["iPhone10,2", "iPhone10,5"],
            introduction: 2017.introductionYear,
            supportId: "SP768",
            launchOSVersion: "11",
            unsupportedOSVersion: "17",
            image: "https://cdsassets.apple.com/live/7WUAS350/images/iphone/iphone-8-plus/iphone-8plus-colors.jpg",
            capabilities: [.plus, .lightning, .wirelessCharging, .biometrics(.touchID), .nfc, .force3DTouch, .ringerSwitch, .barometer, .applePay],
            models: ["A1864", "A1897", "A1898", "A1899"],
            colors: .iPhone8,
            cpu: .a11,
            cameras: [.main12MP, .telephoto, .faceTimeHD1080p],
            cellular: .lte,
            screen: .i55),
        iPhone(
            officialName: "iPhone X",
            identifiers: ["iPhone10,3", "iPhone10,6"],
            introduction: 2017.introductionYear,
            supportId: "SP770",
            launchOSVersion: "11.1",
            unsupportedOSVersion: "17",
            image: "https://cdsassets.apple.com/live/7WUAS350/images/iphone/iphone-x-colors.jpg",
            capabilities: [.lightning, .wirelessCharging, .biometrics(.faceID), .esim, .nfc, .force3DTouch, .roundedCorners, .notch, .ringerSwitch, .barometer, .applePay],
            models: ["A1865", "A1901", "A1902"],
            colors: .iPhoneX,
            cpu: .a11,
            cameras: [.main12MP, .telephoto, .trueDepth7MP],
            cellular: .lte,
            screen: .i58),
        iPhone(
            officialName: "iPhone Xs",
            identifiers: ["iPhone11,2"],
            introduction: 2018.introductionYear,
            supportId: "SP779",
            launchOSVersion: "12",
            unsupportedOSVersion: "26",
            image: "https://cdsassets.apple.com/live/7WUAS350/images/iphone/iphone-xs-colors.jpg",
            capabilities: [.lightning, .wirelessCharging, .biometrics(.faceID), .esim, .nfc, .force3DTouch, .roundedCorners, .notch, .ringerSwitch, .barometer, .applePay],
            models: ["A1920", "A2097", "A2098", "A2099", "A2100"],
            colors: .iPhoneXs,
            cpu: .a12,
            cameras: [.main12MP, .telephoto, .trueDepth7MP],
            cellular: .lte,
            screen: .i58),
        iPhone(
            officialName: "iPhone Xs Max",
            identifiers: ["iPhone11,4", "iPhone11,6"],
            introduction: 2018.introductionYear,
            supportId: "SP780",
            launchOSVersion: "12",
            unsupportedOSVersion: "26",
            image: "https://cdsassets.apple.com/live/7WUAS350/images/iphone/iphone-xs-max-colors.jpg",
            capabilities: [.max, .lightning, .wirelessCharging, .biometrics(.faceID), .esim, .nfc, .force3DTouch, .roundedCorners, .notch, .ringerSwitch, .barometer, .applePay],
            models: ["A1921", "A2101", "A2102", "A2103", "A2104"],
            colors: .iPhoneXs,
            cpu: .a12,
            cameras: [.main12MP, .telephoto, .trueDepth7MP],
            cellular: .lte,
            screen: .i65),
        iPhone(
            officialName: "iPhone Xʀ",
            identifiers: ["iPhone11,8"],
            introduction: 2018.introductionYear,
            supportId: "SP781",
            launchOSVersion: "12",
            unsupportedOSVersion: "26",
            image: "https://cdsassets.apple.com/live/7WUAS350/images/iphone/iphone-xr/identify-iphone-xr-colors.jpg",
            capabilities: [.lightning, .wirelessCharging, .biometrics(.faceID), .esim, .nfc, .roundedCorners, .notch, .ringerSwitch, .barometer, .applePay],
            models: ["A1984", "A2105", "A2106", "A2107", "A2108"],
            colors: .iPhoneXʀ,
            cpu: .a12,
            cameras: [.main12MP, .trueDepth7MP],
            cellular: .lte,
            screen: .i61x828),
        iPhone(
            officialName: "iPhone 11",
            identifiers: ["iPhone12,1"],
            introduction: 2019.introductionYear,
            supportId: "SP804",
            launchOSVersion: "13",
            unsupportedOSVersion: nil,
            image: "https://cdsassets.apple.com/live/7WUAS350/images/iphone/identify-iphone-11-colors.jpg",
            capabilities: [.lightning, .wirelessCharging, .biometrics(.faceID), .esim, .nfc, .roundedCorners, .notch, .ringerSwitch, .barometer, .applePay],
            models: ["A2111", "A2223", "A2221"],
            colors: .iPhone11,
            cpu: .a13,
            cameras: [.main12MP, .ultraWide, .trueDepth12MP],
            cellular: .lte,
            screen: .i61x828),
        iPhone(
            officialName: "iPhone 11 Pro",
            identifiers: ["iPhone12,3"],
            introduction: 2019.introductionYear,
            supportId: "SP805",
            launchOSVersion: "13",
            unsupportedOSVersion: nil,
            image: "https://cdsassets.apple.com/live/7WUAS350/images/iphone/identify-iphone-11pro.jpg",
            capabilities: [.pro, .lightning, .wirelessCharging, .biometrics(.faceID), .esim, .nfc, .roundedCorners, .notch, .ringerSwitch, .barometer, .applePay],
            models: ["A2160", "A2217", "A2215"],
            colors: .iPhone11Pro,
            cpu: .a13,
            cameras: [.main12MP, .ultraWide, .telephoto, .trueDepth12MP],
            cellular: .lte,
            screen: .i58),
        iPhone(
            officialName: "iPhone 11 Pro Max",
            identifiers: ["iPhone12,5"],
            introduction: 2019.introductionYear,
            supportId: "SP806",
            launchOSVersion: "13",
            unsupportedOSVersion: nil,
            image: "https://cdsassets.apple.com/live/7WUAS350/images/iphone/identify-iphone-11pro-max.jpg",
            capabilities: [.pro, .max, .lightning, .wirelessCharging, .biometrics(.faceID), .esim, .nfc, .roundedCorners, .notch, .ringerSwitch, .barometer, .applePay],
            models: ["A2161", "A2220", "A2218"],
            colors: .iPhone11Pro,
            cpu: .a13,
            cameras: [.main12MP, .ultraWide, .telephoto, .trueDepth12MP],
            cellular: .lte,
            screen: .i65),
        iPhone(
            officialName: "iPhone SE (2nd generation)",
            identifiers: ["iPhone12,8"],
            introduction: 2020.introductionYear,
            supportId: "SP820",
            launchOSVersion: "13.4.1",
            unsupportedOSVersion: nil,
            image: "https://cdsassets.apple.com/live/7WUAS350/images/iphone/iphone-se/iphone-se-2nd-gen-colors.jpg",
            capabilities: [.lightning, .wirelessCharging, .biometrics(.touchID), .esim, .nfc, .ringerSwitch, .barometer, .applePay],
            models: ["A2275", "A2298", "A2296"],
            colors: .iPhoneSE2,
            cpu: .a13,
            cameras: [.main12MP, .faceTimeHD1080p],
            cellular: .lte,
            screen: .i47),
        iPhone(
            officialName: "iPhone 12",
            identifiers: ["iPhone13,2"],
            introduction: 2020.introductionYear,
            supportId: "SP830",
            launchOSVersion: "14.1",
            unsupportedOSVersion: nil,
            image: "https://cdsassets.apple.com/live/7WUAS350/images/iphone/2021-iphone12-colors.png",
            capabilities: [.lightning, .wirelessCharging, .magSafe, .biometrics(.faceID), .esim, .nfc, .roundedCorners, .notch, .ringerSwitch, .barometer, .applePay],
            models: ["A2172", "A2402", "A2404", "A2403"],
            colors: .iPhone12,
            cpu: .a14,
            cameras: [.main12MP, .ultraWide, .trueDepth12MP],
            cellular: .fiveG,
            screen: .i61x1170),
        iPhone(
            officialName: "iPhone 12 mini",
            identifiers: ["iPhone13,1"],
            introduction: 2020.introductionYear,
            supportId: "SP829",
            launchOSVersion: "14.2",
            unsupportedOSVersion: nil,
            image: "https://cdsassets.apple.com/live/7WUAS350/images/iphone/2021-iphone12-mini-colors.png",
            capabilities: [.mini, .lightning, .wirelessCharging, .magSafe, .biometrics(.faceID), .esim, .nfc, .roundedCorners, .notch, .ringerSwitch, .barometer, .applePay],
            models: ["A2176", "A2398", "A2400", "A2399"],
            colors: .iPhone12,
            cpu: .a14,
            cameras: [.main12MP, .ultraWide, .trueDepth12MP],
            cellular: .fiveG,
            screen: .i54),
        iPhone(
            officialName: "iPhone 12 Pro",
            identifiers: ["iPhone13,3"],
            introduction: 2020.introductionYear,
            supportId: "SP831",
            launchOSVersion: "14.1",
            unsupportedOSVersion: nil,
            image: "https://cdsassets.apple.com/live/7WUAS350/images/iphone/iphone-12-pro/iphone12-pro-colors.jpg",
            capabilities: [.pro, .lightning, .wirelessCharging, .magSafe, .biometrics(.faceID), .esim, .nfc, .roundedCorners, .notch, .ringerSwitch, .lidar, .barometer, .applePay],
            models: ["A2341", "A2406", "A2408", "A2407"],
            colors: .iPhone12Pro,
            cpu: .a14,
            cameras: [.main12MP, .ultraWide, .telephoto, .trueDepth12MP],
            cellular: .fiveG,
            screen: .i61x1170),
        iPhone(
            officialName: "iPhone 12 Pro Max",
            identifiers: ["iPhone13,4"],
            introduction: 2020.introductionYear,
            supportId: "SP832",
            launchOSVersion: "14.2",
            unsupportedOSVersion: nil,
            image: "https://cdsassets.apple.com/live/7WUAS350/images/iphone/iphone-12-pro-max/iphone12-pro-max-colors.jpg",
            capabilities: [.pro, .max, .lightning, .wirelessCharging, .magSafe, .biometrics(.faceID), .esim, .nfc, .roundedCorners, .notch, .ringerSwitch, .lidar, .barometer, .applePay],
            models: ["A2342", "A2410", "A2412", "A2411"],
            colors: .iPhone12Pro,
            cpu: .a14,
            cameras: [.main12MP, .ultraWide, .telephoto2½x, .trueDepth12MP],
            cellular: .fiveG,
            screen: .i67x1284),
        iPhone(
            officialName: "iPhone 13",
            identifiers: ["iPhone14,5"],
            introduction: 2021.introductionYear,
            supportId: "SP851",
            launchOSVersion: "15",
            unsupportedOSVersion: nil,
            image: "https://cdsassets.apple.com/live/7WUAS350/images/iphone/2022-spring-iphone13-colors.png",
            capabilities: [.lightning, .wirelessCharging, .magSafe, .biometrics(.faceID), .esim, .dualesim, .nfc, .roundedCorners, .notch, .ringerSwitch, .barometer, .applePay],
            models: ["A2482", "A2631", "A2634", "A2635", "A2633"],
            colors: .iPhone13,
            cpu: .a15,
            cameras: [.main12MP, .ultraWide, .trueDepth12MP],
            cellular: .fiveG,
            screen: .i61x1170),
        iPhone(
            officialName: "iPhone 13 mini",
            identifiers: ["iPhone14,4"],
            introduction: 2021.introductionYear,
            supportId: "SP847",
            launchOSVersion: "15",
            unsupportedOSVersion: nil,
            image: "https://cdsassets.apple.com/live/7WUAS350/images/iphone/2022-iphone13-mini-colors.png",
            capabilities: [.mini, .lightning, .wirelessCharging, .magSafe, .biometrics(.faceID), .esim, .dualesim, .nfc, .roundedCorners, .notch, .ringerSwitch, .barometer, .applePay],
            models: ["A2481", "A2626", "A2629", "A2630", "A2628"],
            colors: .iPhone13,
            cpu: .a15,
            cameras: [.main12MP, .ultraWide, .trueDepth12MP],
            cellular: .fiveG,
            screen: .i54),
        iPhone(
            officialName: "iPhone 13 Pro",
            identifiers: ["iPhone14,2"],
            introduction: 2021.introductionYear,
            supportId: "SP852",
            launchOSVersion: "15",
            unsupportedOSVersion: nil,
            image: "https://cdsassets.apple.com/live/7WUAS350/images/iphone/2022-spring-iphone13-pro-colors.png",
            capabilities: [.pro, .lightning, .wirelessCharging, .magSafe, .biometrics(.faceID), .esim, .dualesim, .nfc, .roundedCorners, .notch, .ringerSwitch, .lidar, .barometer, .applePay],
            models: ["A2483", "A2636", "A2639", "A2640", "A2638"],
            colors: .iPhone13Pro,
            cpu: .a15,
            cameras: [.main12MP, .ultraWide, .telephoto3x, .trueDepth12MP],
            cellular: .fiveG,
            screen: .i61x1170),
        iPhone(
            officialName: "iPhone 13 Pro Max",
            identifiers: ["iPhone14,3"],
            introduction: 2021.introductionYear,
            supportId: "SP848",
            launchOSVersion: "15",
            unsupportedOSVersion: nil,
            image: "https://cdsassets.apple.com/live/7WUAS350/images/iphone/2022-spring-iphone13-pro-max-colors.png",
            capabilities: [.pro, .max, .lightning, .wirelessCharging, .magSafe, .biometrics(.faceID), .esim, .dualesim, .nfc, .roundedCorners, .notch, .ringerSwitch, .lidar, .barometer, .applePay],
            models: ["A2484", "A2641", "A2644", "A2645", "A2643"],
            colors: .iPhone13Pro,
            cpu: .a15,
            cameras: [.main12MP, .ultraWide, .telephoto3x, .trueDepth12MP],
            cellular: .fiveG,
            screen: .i67x1284),
        iPhone(
            officialName: "iPhone SE (3rd generation)",
            identifiers: ["iPhone14,6"],
            introduction: 2022.introductionYear,
            supportId: "SP867",
            launchOSVersion: "15.4",
            unsupportedOSVersion: nil,
            image: "https://cdsassets.apple.com/live/7WUAS350/images/iphone/iphone-se-3rd-gen-colors.png",
            capabilities: [.lightning, .wirelessCharging, .magSafe, .biometrics(.touchID), .esim, .dualesim, .nfc, .ringerSwitch, .barometer, .applePay],
            models: ["A2595", "A2782", "A2784", "A2785", "A2783"],
            colors: .iPhoneSE3,
            cpu: .a15,
            cameras: [.main12MP, .faceTimeHD1080p],
            cellular: .fiveG,
            screen: .i47),
        iPhone(
            officialName: "iPhone 14",
            identifiers: ["iPhone14,7"],
            introduction: 2022.introductionYear,
            supportId: "SP873",
            launchOSVersion: "16",
            unsupportedOSVersion: nil,
            image: "https://cdsassets.apple.com/live/7WUAS350/images/iphone/iphone-14-colors-spring-2023.png",
            capabilities: [.lightning, .wirelessCharging, .magSafe, .biometrics(.faceID), .esim, .dualesim, .nfc, .roundedCorners, .notch, .ringerSwitch, .barometer, .crashDetection, .applePay],
            models: ["A2649", "A2881", "A2884", "A2883", "A2882"],
            colors: .iPhone14,
            cpu: .a15,
            cameras: [.main12MP, .ultraWide, .trueDepth12MP],
            cellular: .fiveG,
            screen: .i61x1170),
        iPhone(
            officialName: "iPhone 14 Plus",
            identifiers: ["iPhone14,8"],
            introduction: 2022.introductionYear,
            supportId: "SP874",
            launchOSVersion: "16",
            unsupportedOSVersion: nil,
            image: "https://cdsassets.apple.com/live/7WUAS350/images/iphone/iphone-14-plus-colors-spring-2023.png",
            capabilities: [.plus, .lightning, .wirelessCharging, .magSafe, .biometrics(.faceID), .esim, .dualesim, .nfc, .roundedCorners, .notch, .ringerSwitch, .barometer, .crashDetection, .applePay],
            models: ["A2632", "A2885", "A2888", "A2887", "A2886"],
            colors: .iPhone14,
            cpu: .a15,
            cameras: [.main12MP, .ultraWide, .trueDepth12MP],
            cellular: .fiveG,
            screen: .i67x1284),
        iPhone(
            officialName: "iPhone 14 Pro",
            identifiers: ["iPhone15,2"],
            introduction: 2022.introductionYear,
            supportId: "SP875",
            launchOSVersion: "16",
            unsupportedOSVersion: nil,
            image: "https://cdsassets.apple.com/live/7WUAS350/images/iphone/iphone-14-pro-colors.png",
            capabilities: [.pro, .lightning, .wirelessCharging, .magSafe, .biometrics(.faceID), .esim, .dualesim, .nfc, .roundedCorners, .dynamicIsland, .alwaysOnDisplay, .ringerSwitch, .lidar, .barometer, .crashDetection, .applePay],
            models: ["A2650", "A2889", "A2892", "A2891", "A2890"],
            colors: .iPhone14Pro,
            cpu: .a16,
            cameras: [.main48MP, .ultraWide, .telephoto3x, .trueDepth12MP],
            cellular: .fiveG,
            screen: .i61x1179),
        iPhone(
            officialName: "iPhone 14 Pro Max",
            identifiers: ["iPhone15,3"],
            introduction: 2022.introductionYear,
            supportId: "SP876",
            launchOSVersion: "16",
            unsupportedOSVersion: nil,
            image: "https://cdsassets.apple.com/live/7WUAS350/images/iphone/iphone-14-pro-max-colors.png",
            capabilities: [.pro, .max, .lightning, .wirelessCharging, .magSafe, .biometrics(.faceID), .esim, .dualesim, .nfc, .roundedCorners, .dynamicIsland, .alwaysOnDisplay, .ringerSwitch, .lidar, .barometer, .crashDetection, .applePay],
            models: ["A2651", "A2893", "A2896", "A2895", "A2894"],
            colors: .iPhone14Pro,
            cpu: .a16,
            cameras: [.main48MP, .ultraWide, .telephoto3x, .trueDepth12MP],
            cellular: .fiveG,
            screen: .i67x1290),
        iPhone(
            officialName: "iPhone 15",
            identifiers: ["iPhone15,4"],
            introduction: "2023-09-22",
            supportId: "SP901",
            launchOSVersion: "17.0.2",
            unsupportedOSVersion: nil,
            image: "https://cdsassets.apple.com/live/7WUAS350/images/iphone/fall-2023-iphone-colors-iphone-15.png",
            capabilities: [.usbC, .wirelessCharging, .magSafe, .biometrics(.faceID), .esim, .dualesim, .nfc, .roundedCorners, .dynamicIsland, .ringerSwitch, .actionButton, .barometer, .crashDetection, .applePay],
            models: ["A2846", "A3089", "A3092", "A3090"],
            colors: .iPhone15,
            cpu: .a16,
            cameras: [.main48MP, .ultraWide, .trueDepth12MP],
            cellular: .fiveG,
            screen: .i61x1179),
        iPhone(
            officialName: "iPhone 15 Plus",
            identifiers: ["iPhone15,5"],
            introduction: "2023-09-22",
            supportId: "SP902",
            launchOSVersion: "17.0.2",
            unsupportedOSVersion: nil,
            image: "https://cdsassets.apple.com/live/7WUAS350/images/iphone/fall-2023-iphone-colors-iphone-15-plus.png",
            capabilities: [.plus, .usbC, .wirelessCharging, .magSafe, .biometrics(.faceID), .esim, .dualesim, .nfc, .roundedCorners, .dynamicIsland, .ringerSwitch, .actionButton, .barometer, .crashDetection, .applePay],
            models: ["A2847", "A3093", "A3096", "A3094"],
            colors: .iPhone15,
            cpu: .a16,
            cameras: [.main48MP, .ultraWide, .trueDepth12MP],
            cellular: .fiveG,
            screen: .i67x1290),
        iPhone(
            officialName: "iPhone 15 Pro",
            identifiers: ["iPhone16,1"],
            introduction: "2023-09-22",
            supportId: "SP903",
            launchOSVersion: "17.0.2",
            unsupportedOSVersion: nil,
            image: "https://cdsassets.apple.com/live/7WUAS350/images/iphone/fall-2023-iphone-colors-iphone-15-pro.png",
            capabilities: [.pro, .usbC, .wirelessCharging, .magSafe, .biometrics(.faceID), .esim, .dualesim, .nfc, .roundedCorners, .dynamicIsland, .alwaysOnDisplay, .actionButton, .lidar, .barometer, .crashDetection, .applePay, .appleIntelligence],
            models: ["A2848", "A3101", "A3104", "A3102"],
            colors: .iPhone15Pro,
            cpu: .a17pro,
            cameras: [.main48MP, .ultraWide, .telephoto3x, .trueDepth12MP],
            cellular: .fiveG,
            screen: .i61x1179),
        iPhone(
            officialName: "iPhone 15 Pro Max",
            identifiers: ["iPhone16,2"],
            introduction: "2023-09-22",
            supportId: "SP904",
            launchOSVersion: "17.0.2",
            unsupportedOSVersion: nil,
            image: "https://cdsassets.apple.com/live/7WUAS350/images/iphone/fall-2023-iphone-colors-iphone-15-pro-max.png",
            capabilities: [.pro, .max, .usbC, .wirelessCharging, .magSafe, .biometrics(.faceID), .esim, .dualesim, .nfc, .roundedCorners, .dynamicIsland, .alwaysOnDisplay, .actionButton, .lidar, .barometer, .crashDetection, .applePay, .appleIntelligence],
            models: ["A2849", "A3105", "A3108", "A3106"],
            colors: .iPhone15Pro,
            cpu: .a17pro,
            cameras: [.main48MP, .ultraWide, .telephoto5x, .trueDepth12MP],
            cellular: .fiveG,
            screen: .i67x1290),

        iPhone(
            officialName: "iPhone 16",
            identifiers: ["iPhone17,3"],
            introduction: 2024.introductionYear,
            supportId: "121029",
            launchOSVersion: "18",
            unsupportedOSVersion: nil,
            image: "https://cdsassets.apple.com/live/7WUAS350/images/iphone/iphone-16-colors.png",
            capabilities: [.usbC, .wirelessCharging, .magSafe, .biometrics(.faceID), .esim, .dualesim, .nfc, .roundedCorners, .dynamicIsland, .actionButton, .cameraControl, .barometer, .crashDetection, .applePay, .appleIntelligence],
            models: ["A3081", "A3286", "A3288", "A3287"],
            colors: .iPhone16,
            cpu: .a18,
            cameras: [.fusionMain, .ultraWide, .trueDepth12MP],
            cellular: .fiveG,
            screen: .i61x1179),
        iPhone(
            officialName: "iPhone 16 Plus",
            identifiers: ["iPhone17,4"],
            introduction: 2024.introductionYear,
            supportId: "121030",
            launchOSVersion: "18",
            unsupportedOSVersion: nil,
            image: "https://cdsassets.apple.com/live/7WUAS350/images/iphone/iphone-16-plus-colors.png",
            capabilities: [.plus, .usbC, .wirelessCharging, .magSafe, .biometrics(.faceID), .esim, .dualesim, .nfc, .roundedCorners, .dynamicIsland, .actionButton, .cameraControl, .barometer, .crashDetection, .applePay, .appleIntelligence],
            models: ["A3082", "A3289", "A3291", "A3290"],
            colors: .iPhone16,
            cpu: .a18,
            cameras: [.fusionMain, .ultraWide, .trueDepth12MP],
            cellular: .fiveG,
            screen: .i67x1290),
        iPhone(
            officialName: "iPhone 16 Pro",
            identifiers: ["iPhone17,1"],
            introduction: 2024.introductionYear,
            supportId: "121031",
            launchOSVersion: "18",
            unsupportedOSVersion: nil,
            image: "https://cdsassets.apple.com/live/7WUAS350/images/iphone/iphone-16-pro-colors.png",
            capabilities: [.pro, .usbC, .wirelessCharging, .magSafe, .biometrics(.faceID), .esim, .dualesim, .nfc, .roundedCorners, .dynamicIsland, .alwaysOnDisplay, .actionButton, .cameraControl, .lidar, .barometer, .crashDetection, .applePay, .appleIntelligence],
            models: ["A3083", "A3292", "A3294", "A3293"],
            colors: .iPhone16Pro,
            cpu: .a18pro,
            cameras: [.fusionMain, .ultraWide48MP, .telephoto5x, .trueDepth12MP],
            cellular: .fiveG,
            screen: .i63),
        iPhone(
            officialName: "iPhone 16 Pro Max",
            identifiers: ["iPhone17,2"],
            introduction: 2024.introductionYear,
            supportId: "121032",
            launchOSVersion: "18",
            unsupportedOSVersion: nil,
            image: "https://cdsassets.apple.com/live/7WUAS350/images/iphone/iphone-16-pro-max-colors.png",
            capabilities: [.pro, .max, .usbC, .wirelessCharging, .magSafe, .biometrics(.faceID), .esim, .dualesim, .nfc, .roundedCorners, .dynamicIsland, .alwaysOnDisplay, .actionButton, .cameraControl, .lidar, .barometer, .crashDetection,  .applePay, .appleIntelligence],
            models: ["A3084", "A3295", "A3297", "A3296"],
            colors: .iPhone16Pro,
            cpu: .a18pro,
            cameras: [.fusionMain, .ultraWide48MP, .telephoto5x, .trueDepth12MP],
            cellular: .fiveG,
            screen: .i69),

        iPhone(
            officialName: "iPhone 16e",
            identifiers: ["iPhone17,5"],
            introduction: 2025.introductionYear,
            supportId: "122208",
            launchOSVersion: "18.3.1",
            unsupportedOSVersion: nil,
            image: "https://cdsassets.apple.com/live/7WUAS350/images/iphone/iphone-16e/iphone-16e-colors.png",
            capabilities: [.usbC, .wirelessCharging, .biometrics(.faceID), .esim, .dualesim, .nfc, .roundedCorners, .notch, .actionButton, .barometer, .crashDetection, .applePay, .appleIntelligence],
            models: ["A3212", "A3408", "A3410", "A3409"],
            colors: .iPhone16e,
            cpu: .a18,
            cameras: [.fusionMain, .trueDepth12MP],
            cellular: .fiveG,
            screen: .i61x1170),

        iPhone(
            officialName: "iPhone 17",
            identifiers: ["iPhone18,3"],
            introduction: "2025-09-12",
            supportId: "125089",
            launchOSVersion: "26",
            unsupportedOSVersion: nil,
            image: "https://cdsassets.apple.com/live/7WUAS350/images/iphone/iphone-17-colors.png",
            capabilities: [.usbC, .wirelessCharging, .magSafe, .biometrics(.faceID), .esim, .dualesim, .nfc, .roundedCorners, .dynamicIsland, .alwaysOnDisplay, .actionButton, .cameraControl, .barometer, .crashDetection, .applePay, .appleIntelligence],
            models: ["A3258", "A3519", "A3521", "A3520"],
            colors: .iPhone17,
            cpu: .a19,
            cameras: [.fusionMain, .fusionUltraWide, .centerStage],
            cellular: .fiveG,
            screen: .i63),
        iPhone(
            officialName: "iPhone Air",
            identifiers: ["iPhone18,4"],
            introduction: "2025-09-12",
            supportId: "125092",
            launchOSVersion: "26",
            unsupportedOSVersion: nil,
            image: "https://cdsassets.apple.com/live/7WUAS350/images/iphone/iphone-air-colors.png",
            capabilities: [.air, .usbC, .wirelessCharging, .magSafe, .biometrics(.faceID), .esim, .dualesim, .nfc, .roundedCorners, .dynamicIsland, .alwaysOnDisplay, .actionButton, .cameraControl, .barometer, .crashDetection, .applePay, .appleIntelligence],
            models: ["A3260", "A3516", "A3518", "A3517"],
            colors: .iPhoneAir,
            cpu: .a19pro,
            cameras: [.fusionMain, .centerStage],
            cellular: .fiveG,
            screen: .i65Air),
        iPhone(
            officialName: "iPhone 17 Pro",
            identifiers: ["iPhone18,1"],
            introduction: "2025-09-12",
            supportId: "125090",
            launchOSVersion: "26",
            unsupportedOSVersion: nil,
            image: "https://cdsassets.apple.com/live/7WUAS350/images/iphone/iphone-17-pro-colors.png",
            capabilities: [.pro, .usbC, .wirelessCharging, .magSafe, .biometrics(.faceID), .esim, .dualesim, .nfc, .roundedCorners, .dynamicIsland, .alwaysOnDisplay, .actionButton, .cameraControl, .lidar, .barometer, .crashDetection, .applePay, .appleIntelligence],
            models: ["A3256", "A3522", "A3524", "A3523"],
            colors: .iPhone17Pro,
            cpu: .a19pro,
            cameras: [.fusionMain, .fusionUltraWide, .fusionTelephoto, .centerStage],
            cellular: .fiveG,
            screen: .i63),
        iPhone(
            officialName: "iPhone 17 Pro Max",
            identifiers: ["iPhone18,2"],
            introduction: "2025-09-12",
            supportId: "125091",
            launchOSVersion: "26",
            unsupportedOSVersion: nil,
            image: "https://cdsassets.apple.com/live/7WUAS350/images/iphone/iphone-17-pro-max-colors.png",
            capabilities: [.pro, .max, .usbC, .wirelessCharging, .magSafe, .biometrics(.faceID), .esim, .dualesim, .nfc, .roundedCorners, .dynamicIsland, .alwaysOnDisplay, .actionButton, .cameraControl, .lidar, .barometer, .crashDetection, .applePay, .appleIntelligence],
            models: ["A3257", "A3525", "A3527", "A3526"],
            colors: .iPhone17Pro,
            cpu: .a19pro,
            cameras: [.fusionMain, .fusionUltraWide, .fusionTelephoto, .centerStage],
            cellular: .fiveG,
            screen: .i69),
        // Get images and support links/IDs from: https://support.apple.com/en-us/108044
    ]
}
