//
//  Macs.swift
//  Device
//
//  Created by Ben Ku on 4/18/25.
//

import Compatibility

public struct Mac: IdiomType {
    public enum Form: String, Hashable, CaseIterable, CaseNameConvertible, Sendable {
        /// original cheese grater
        case macProGen1 = "macpro.gen1"
        /// trash can
        case macProGen2 = "macpro.gen2"
        /// silver handle circles
        case macProGen3 = "macpro.gen3"
//        case macProGen3Server = "macpro.gen3.server" // MacPro Rack configuration
        case macBook = "macbook"
        /// magSafe 2
        case macBookGen1 = "macbook.gen1"
        /// magSafe 3, notch
        case macBookGen2 = "macbook.gen2"
        case macMini = "macmini"
        case macStudio = "macstudio"
        case iMac = "desktopcomputer"
        /// Form-specific capabilities
        public var capabilities: Capabilities {
            switch self {
            case .macProGen1:
                [.pro, .headphoneJack, .ethernet]
            case .macProGen2:
                Mac.Form.macProGen1.capabilities.union([.thunderbolt])
            case .macProGen3:
                Mac.Form.macProGen2.capabilities.union([.usbC])
            case .macBook:
                [.headphoneJack, .battery]
            case .macBookGen1:
                Mac.Form.macBook.capabilities.union([.cameras([.faceTimeHD720p]), .magSafe2])
            case .macBookGen2:
                Mac.Form.macBook.capabilities.union([.usbC, .thunderbolt, .notch, .cameras([.faceTimeHD1080p]), .biometrics(.touchID), .magSafe3])
            case .macMini:
                [.mini, .headphoneJack, .ethernet]
            case .macStudio:
                [.headphoneJack, .ethernet, .usbC, .thunderbolt]
            case .iMac:
                [.headphoneJack]
            }
        }
        // TODO: func to convert an identifier to a form (Macmini, MacPro, MacBookPro, MacBook, MacBookAir, etc)
        public var hasScreen: Bool {
            switch self {
            case .macProGen1:
                return false
            case .macProGen2:
                return false
            case .macProGen3:
                return false
            case .macBook:
                return true
            case .macBookGen1:
                return true
            case .macBookGen2:
                return true
            case .macMini:
                return false
            case .macStudio:
                return false
            case .iMac:
                return true
            }
        }
    }
    
    public let device: Device
    public init(knownDevice: Device) {
        self.device = knownDevice
    }

    public init(
        officialName: String,
        identifiers: [String],
        introduction: DateString,
        supportId: String,
        launchOSVersion: Version,
        unsupportedOSVersion: Version?,
        form: Form, // will indicate if there is a battery or not (only MacBooks have batteries)
        image: String?,
        capabilities: Capabilities = [],
        models: [String] = [],
        colors: [MaterialColor],
        cpu: CPU,
        screen: Screen? = nil
    )
    {
        var capabilities = capabilities.union(form.capabilities).union([
            // assume for all models we are working with here.  If this changes, will remove from defaults.
            .headphoneJack,
            .macForm(form) // will this be problematic with zeroing out defaults or base model?  No because adding the new form should replace old?
        ])
        if let screen {
            capabilities.formUnion([.screen(screen)])
        } else if form.hasScreen {
            capabilities.formUnion([.screen(.undefined)])
        }
        device = Device(
            idiom: .mac,
            officialName: officialName,
            identifiers: identifiers,
            introduction: introduction,
            supportId: supportId,
            launchOSVersion: launchOSVersion,
            unsupportedOSVersion: unsupportedOSVersion,
            image: image,
            capabilities: capabilities,
            models: models,
            colors: colors,
            cpu: cpu)
    }
    
    init(identifier: String) {
        self.init(
            officialName: "Unknown Mac",
            identifiers: [identifier],
            introduction: .defaultBlank,
            supportId: .unknownSupportId,
            launchOSVersion: .zero,
            unsupportedOSVersion: nil,
            form: .macMini, // no default battery
            image: nil,
            capabilities: identifier == .base ? [] : [
                // defaults for new unknown devices
                .usbC, .thunderbolt
            ],
            models: [],
            colors: .default,
            cpu: .unknown
        )
    }
    
    /// Mac form enum (unwrapped from capabilities)
    public var form: Form {
        return capabilities.macForm ?? .macStudio // should never be nil but here just in case.
    }
    
    /// An SF Symbol name for an icon representing the device.  If no specific variant exists, uses a generic symbol for device idiom.
    public var symbolName: String {
        return self.form.rawValue
    }

    static let all = [
        // TODO: We need a lot more of the macs here!  Please help fill these out via a pull request.
        // Support IDs and images can be found here: https://support.apple.com/en-us/108054

        // MARK: - iMacs
        Mac(
            officialName: "iMac (24-inch, 2024, Four ports)",
            identifiers: ["Mac16,3"],
            introduction: 2024.introductionYear,
            supportId: "121557",
            launchOSVersion: "15",
            unsupportedOSVersion: nil,
            form: .iMac,
            image: "https://cdsassets.apple.com/live/7WUAS350/images/imac/imac-24in-2024-four-ports-colors.png",
            capabilities: [.thunderbolt, .biometrics(.touchID)],
            models: ["MCR24xx/A", "MD2P4xx/A", "MD2Q4xx/A", "MD2T4xx/A", "MD2U4xx/A", "MD2V4xx/A", "MD2W4xx/A", "MD2X4xx/A", "MD2Y4xx/A", "MD3A4xx/A", "MD3D4xx/A", "MD3E4xx/A", "MD3F4xx/A", "MD3G4xx/A", "MD3H4xx/A", "MWUU3xx/A", "MWUV3xx/A", "MWUW3xx/A", "MWUX3xx/A", "MWUY3xx/A", "MWV03xx/A", "MWV13xx/A", "MWV33xx/A", "MWV43xx/A", "MWV53xx/A", "MWV63xx/A", "MWV73xx/A", "MWV83xx/A", "MWV93xx/A", "MWVA3xx/A", "MWVC3xx/A", "MWVD3xx/A", "MWVE3xx/A", "MWVF3xx/A", "MWVG3xx/A", "MWVH3xx/A", "MWVJ3xx/A", "MWVK3xx/A", "MWVL3xx/A", "MWVN3xx/A", "MWVP3xx/A", "MWVQ3xx/A", "MWVR3xx/A"],
            colors: .iMac2024,
            cpu: .m4),
        Mac(
            officialName: "iMac (24-inch, 2024, Two ports)",
            identifiers: ["Mac16,2"],
            introduction: 2024.introductionYear,
            supportId: "121556",
            launchOSVersion: "15",
            unsupportedOSVersion: nil,
            form: .iMac,
            image: "https://cdsassets.apple.com/live/7WUAS350/images/imac/imac-24in-2024-two-ports-colors.png",
            capabilities: [.thunderbolt, .biometrics(.touchID)],
            models: ["MWUD3xx/A", "MWUE3xx/A", "MWUF3xx/A", "MWUG3xx/A", "MWUH3xx/A", "MWUJ3xx/A", "MWUK3xx/A", "MWUL3xx/A", "MWUN3xx/A", "MWUPxx/A", "MWUQ3xx/A", "MWUR3xx/A", "MWUT3xx/A"],
            colors: .iMac2024,
            cpu: .m4),
        Mac(
            officialName: "iMac (24-inch, 2023, Four ports)",
            identifiers: ["Mac15,5"],
            introduction: 2023.introductionYear,
            supportId: "117734",
            launchOSVersion: "13.5",
            unsupportedOSVersion: nil,
            form: .iMac,
            image: "https://cdsassets.apple.com/live/7WUAS350/images/imac/imac-24in-2023-four-ports-colors.png",
            capabilities: [.thunderbolt, .biometrics(.touchID)],
            models: ["MQRJ3xx/A", "MQRK3xx/A", "MQRL3xx/A", "MQRM3xx/A", "MQRN3xx/A", "MQRP3xx/A", "MQRQ3xx/A", "MQRR3xx/A", "MQRT3xx/A", "MQRU3xx/A", "MQRV3xx/A", "MQRW3xx/A", "MQRX3xx/A", "MQRY3xx/A"],
            colors: .iMac,
            cpu: .m3),
        Mac(
            officialName: "iMac (24-inch, 2023, Two ports)",
            identifiers: ["Mac15,4"],
            introduction: 2023.introductionYear,
            supportId: "117733",
            launchOSVersion: "13.5",
            unsupportedOSVersion: nil,
            form: .iMac,
            image: "https://cdsassets.apple.com/live/7WUAS350/images/imac/imac-24in-2023-two-ports-colors.png",
            capabilities: [.thunderbolt, .biometrics(.touchID)],
            models: ["MQR93xx/A", "MQRA3xx/A", "MQRC3xx/A", "MQRD3xx/A"],
            colors: .iMac2Ports,
            cpu: .m3),
        Mac(
            officialName: "iMac (24-inch, M1, 2021)", // four ports
            identifiers: ["iMac21,1"],
            introduction: 2021.introductionYear,
            supportId: "111895",
            launchOSVersion: "11.3",
            unsupportedOSVersion: nil,
            form: .iMac,
            image: "https://cdsassets.apple.com/live/7WUAS350/images/imac/id-imac-24-2021.png",
            capabilities: [.thunderbolt, .biometrics(.touchID)],
            models: ["MGPC3xx/A", "MGPD3xx/A", "MGPF3xx/A", "MGPG3xx/A", "MGPH3xx/A", "MGPJ3xx/A", "MGPK3xx/A", "MGPL3xx/A", "MGPM3xx/A", "MGPN3xx/A", "MGPP3xx/A", "MGPQ3xx/A", "MGPR3xx/A", "MGPT3xx/A"],
            colors: .iMac,
            cpu: .m1),
        Mac(
            officialName: "iMac (24-inch, M1, 2021)", // two ports
            identifiers: ["iMac21,2"],
            introduction: 2021.introductionYear,
            supportId: "111895", // SP839
            launchOSVersion: "11.3",
            unsupportedOSVersion: nil,
            form: .iMac,
            image: "https://cdsassets.apple.com/live/7WUAS350/images/imac/id-imac-24-2021-2.png",
            capabilities: [.thunderbolt, .biometrics(.touchID)],
            models: ["MGTF3xx/a", "MJV83xx/a", "MJV93xx/a", "MJVA3xx/a"],
            colors: .iMac2Ports,
            cpu: .m1),
        Mac( // TODO: Duplicate so there are separate entries??
            officialName: "iMac (Retina 5K, 27-inch, 2020)",
            identifiers: ["iMac20,1", "iMac20,2"],
            introduction: 2020.introductionYear,
            supportId: "111913", // SP821
            launchOSVersion: "10.15.6",
            unsupportedOSVersion: nil,
            form: .iMac,
            image: "https://cdsassets.apple.com/live/7WUAS350/images/imac/imac-27-2020.jpg",
            capabilities: [.thunderbolt],
            models: ["MXWT2xx/A", "MXWU2xx/A", "MXWV2xx/A"],
            colors: [.silverLight],
            cpu: .intel),
        Mac(
            officialName: "iMac (Retina 5K, 27-inch, 2019)",
            identifiers: ["iMac19,1"],
            introduction: 2019.introductionYear,
            supportId: "111998",
            launchOSVersion: "10.14.4",
            unsupportedOSVersion: "26",
            form: .iMac,
            image: "https://cdsassets.apple.com/live/7WUAS350/images/imac/imac-27-2019.jpg",
            capabilities: [.usbC],
            models: ["MRQYxx/A", "MRR0xx/A", "MRR1xx/A"],
            colors: [.silverLight],
            cpu: .intel),
        Mac(
            officialName: "iMac (Retina 4K, 21.5-inch, 2019)",
            identifiers: ["iMac19,2"],
            introduction: 2019.introductionYear,
            supportId: "111963",
            launchOSVersion: "10.14.4",
            unsupportedOSVersion: "26",
            form: .iMac,
            image: "https://cdsassets.apple.com/live/7WUAS350/images/imac/imac-21-5-2019.jpg",
            capabilities: [.usbC],
            models: ["MRT3xx/A", "MRT4xx/A", "MHK23xx/A"],
            colors: [.silverLight],
            cpu: .intel),
        Mac(
            officialName: "iMac Pro (2017)",
            identifiers: ["iMacPro1,1"],
            introduction: 2017.introductionYear,
            supportId: "111995",
            launchOSVersion: "10.13.2",
            unsupportedOSVersion: "26",
            form: .iMac,
            image: "https://cdsassets.apple.com/live/7WUAS350/images/imac/imac-pro-2017.jpg",
            capabilities: [.pro, .usbC, .biometrics(.touchID)],
            models: ["MQ2Y2xx/A", "MHLV3xx/A"],
            colors: [.macSpacegray],
            cpu: .xeonE5),
        Mac(
            officialName: "iMac (Retina 5K, 27-inch, 2017)",
            identifiers: ["iMac18,3"],
            introduction: 2017.introductionYear,
            supportId: "111969",
            launchOSVersion: "10.12.4",
            unsupportedOSVersion: "14",
            form: .iMac,
            image: "https://cdsassets.apple.com/live/7WUAS350/images/imac/imac-27-2017.jpg",
            capabilities: [.usbC],
            models: ["MNE92xx/A", "MNEA2xx/A", "MNED2xx/A"],
            colors: [.silverLight],
            cpu: .intel),
        Mac(
            officialName: "iMac (Retina 4K, 21.5-inch, 2017)",
            identifiers: ["iMac18,2"],
            introduction: 2017.introductionYear,
            supportId: "112026",
            launchOSVersion: "10.12.4",
            unsupportedOSVersion: "14",
            form: .iMac,
            image: "https://cdsassets.apple.com/live/7WUAS350/images/imac/imac-21-5-2017.jpg",
            capabilities: [.usbC],
            models: ["MNDY2xx/A", "MNE02xx/A"],
            colors: [.silverLight],
            cpu: .intel),
        Mac(
            officialName: "iMac (21.5-inch, 2017)",
            identifiers: ["iMac18,1"],
            introduction: 2017.introductionYear,
            supportId: "111921",
            launchOSVersion: "10.12.4",
            unsupportedOSVersion: "14",
            form: .iMac,
            image: "https://cdsassets.apple.com/live/7WUAS350/images/imac/imac-21-5-2017.jpg", // NOTE: Image needs to be unique?  Why is this?
            capabilities: [.usbC],
            models: ["MMQA2xx/A", "MHK03xx/A"],
            colors: [.silverLight],
            cpu: .intel),
        Mac(
            officialName: "iMac (Retina 5K, 27-inch, Late 2015)",
            identifiers: ["iMac17,1"],
            introduction: 2015.introductionYear,
            supportId: "112035",
            launchOSVersion: "10.11",
            unsupportedOSVersion: "13",
            form: .iMac,
            image: "https://cdsassets.apple.com/live/7WUAS350/images/imac/imac-27-late-2015.jpg",
            capabilities: [.usbC],
            models: ["MK462xx/A", "MK472xx/A", "MK482xx/A"],
            colors: [.silverLight],
            cpu: .intel),
        Mac(
            officialName: "iMac (Retina 4K, 21.5-inch, Late 2015)",
            identifiers: ["iMac16,2"],
            introduction: 2015.introductionYear,
            supportId: "112034",
            launchOSVersion: "10.11",
            unsupportedOSVersion: "13",
            form: .iMac,
            image: "https://cdsassets.apple.com/live/7WUAS350/images/imac/imac-21-5-2015.jpg",
            capabilities: [.usbC],
            models: ["MK452xx/A"],
            colors: [.silverLight],
            cpu: .intel),
        Mac(
            officialName: "iMac (21.5-inch, Late 2015)",
            identifiers: ["iMac16,1"],
            introduction: 2015.introductionYear,
            supportId: "112036",
            launchOSVersion: "10.11",
            unsupportedOSVersion: "13",
            form: .iMac,
            image: "https://cdsassets.apple.com/live/7WUAS350/images/imac/imac-21-5-2015.jpg",
            capabilities: [.usbC],
            models: ["MK142xx/A", "MK442xx/A"],
            colors: [.silverLight],
            cpu: .intel),
        Mac(
            officialName: "iMac (Retina 5K, 27-inch, Mid 2015)",
            identifiers: ["iMac15,1"],
            introduction: 2015.introductionYear,
            supportId: "112434",
            launchOSVersion: "10.10.2",
            unsupportedOSVersion: "12",
            form: .iMac,
            image: "https://cdsassets.apple.com/live/7WUAS350/images/imac/imac-27-mid-2015.jpg",
            capabilities: [.usbC],
            models: ["MF885xx/A"],
            colors: [.silverLight],
            cpu: .intel),
        Mac(
            officialName: "iMac (Retina 5K, 27-inch, Late 2014)",
            identifiers: ["iMac15,1"],
            introduction: 2014.introductionYear,
            supportId: "112436",
            launchOSVersion: "10.10",
            unsupportedOSVersion: "12",
            form: .iMac,
            image: "https://cdsassets.apple.com/live/7WUAS350/images/imac/imac-27-2014.jpg",
            capabilities: [.usbC],
            models: ["MF886xx/A"],
            colors: [.silverLight],
            cpu: .intel),
        Mac(
            officialName: "iMac (21.5-inch, Mid 2014)",
            identifiers: ["iMac14,4"],
            introduction: 2014.introductionYear,
            supportId: "112031",
            launchOSVersion: "10.9.3",
            unsupportedOSVersion: "12",
            form: .iMac,
            image: "https://cdsassets.apple.com/live/7WUAS350/images/imac/imac-21-5-2014.jpg",
            capabilities: [.usbC],
            models: ["MF883xx/A", "MG022xx/A"],
            colors: [.silverLight],
            cpu: .intel),
        Mac(
            officialName: "iMac (27-inch, Late 2013)",
            identifiers: ["iMac14,2"],
            introduction: 2013.introductionYear,
            supportId: "111970",
            launchOSVersion: "10.8.4",
            unsupportedOSVersion: "11",
            form: .iMac,
            image: "https://cdsassets.apple.com/live/7WUAS350/images/imac/imac-27-2013.jpg",
            capabilities: [.usbC],
            models: ["ME086xx/A", "ME088xx/A"],
            colors: [.silverLight],
            cpu: .intel),
        Mac(
            officialName: "iMac (21.5-inch, Late 2013)",
            identifiers: ["iMac14,1"],
            introduction: 2013.introductionYear,
            supportId: "111967",
            launchOSVersion: "10.8.4",
            unsupportedOSVersion: "11",
            form: .iMac,
            image: "https://cdsassets.apple.com/live/7WUAS350/images/imac/imac-21-5-2013.jpg",
            capabilities: [.usbC],
            models: ["ME086xx/A", "ME087xx/A"],
            colors: [.silverLight],
            cpu: .intel),
        Mac(
            officialName: "iMac (27-inch, Late 2012)",
            identifiers: ["iMac13,2"],
            introduction: 2012.introductionYear,
            supportId: "112433",
            launchOSVersion: "10.8.2",
            unsupportedOSVersion: "11",
            form: .iMac,
            image: "https://cdsassets.apple.com/live/7WUAS350/images/imac/imac-27-2012.jpg",
            capabilities: [.usbC],
            models: ["MD095xx/A", "MD096xx/A"],
            colors: [.silverLight],
            cpu: .intel),
        Mac(
            officialName: "iMac (21.5-inch, Late 2012)",
            identifiers: ["iMac13,1"],
            introduction: 2012.introductionYear,
            supportId: "112435",
            launchOSVersion: "10.8.2",
            unsupportedOSVersion: "11",
            form: .iMac,
            image: "https://cdsassets.apple.com/live/7WUAS350/images/imac/imac-21-5-2012.jpg",
            capabilities: [.usbC],
            models: ["MD093xx/A", "MD094xx/A"],
            colors: [.silverLight],
            cpu: .intel),
        Mac(
            officialName: "iMac (27-inch, Mid 2011)",
            identifiers: ["iMac12,2"],
            introduction: 2011.introductionYear,
            supportId: "112569",
            launchOSVersion: "10.6.6",
            unsupportedOSVersion: "10.14",
            form: .iMac,
            image: "https://cdsassets.apple.com/live/7WUAS350/images/imac/imac-27-2011.jpg",
            capabilities: [.usbC],
            models: ["MC813xx/A", "MC814xx/A"],
            colors: [.silverLight],
            cpu: .intel),
        Mac(
            officialName: "iMac (21.5-inch, Mid 2011)",
            identifiers: ["iMac12,1"],
            introduction: 2011.introductionYear,
            supportId: "111983",
            launchOSVersion: "10.6.6",
            unsupportedOSVersion: "10.14",
            form: .iMac,
            image: "https://cdsassets.apple.com/live/7WUAS350/images/imac/imac-21-5-2011.jpg",
            capabilities: [.usbC],
            models: ["MC309xx/A", "MC812xx/A"],
            colors: [.silverLight],
            cpu: .intel),
        Mac(
            officialName: "iMac (27-inch, Mid 2010)",
            identifiers: ["iMac11,3"],
            introduction: 2010.introductionYear,
            supportId: "112566",
            launchOSVersion: "10.6.3",
            unsupportedOSVersion: "10.14",
            form: .iMac,
            image: "https://cdsassets.apple.com/live/7WUAS350/images/imac/imac-27-2010.jpg",
            capabilities: [.usbC],
            models: ["MC510xx/A", "MC511xx/A"],
            colors: [.silverLight],
            cpu: .intel),
        Mac(
            officialName: "iMac (21.5-inch, Mid 2010)",
            identifiers: ["iMac11,2"],
            introduction: 2010.introductionYear,
            supportId: "112567",
            launchOSVersion: "10.6.3",
            unsupportedOSVersion: "10.14",
            form: .iMac,
            image: "https://cdsassets.apple.com/live/7WUAS350/images/imac/imac-21-5-2010.jpg",
            capabilities: [.usbC],
            models: ["MC508xx/A", "MC509xx/A"],
            colors: [.silverLight],
            cpu: .intel),
        Mac(
            officialName: "iMac (27-inch, Late 2009)",
            identifiers: ["iMac10,1"],
            introduction: 2009.introductionYear,
            supportId: "112564",
            launchOSVersion: "10.6.1",
            unsupportedOSVersion: "10.14",
            form: .iMac,
            image: "https://cdsassets.apple.com/live/7WUAS350/images/imac/imac-27-2009-late.jpg",
            capabilities: [.usbC],
            models: ["MB952xx/A", "MB953xx/A"],
            colors: [.silverLight],
            cpu: .intel),
        Mac(
            officialName: "iMac (21.5-inch, Late 2009)",
            identifiers: ["iMac10,1"],
            introduction: 2009.introductionYear,
            supportId: "112565",
            launchOSVersion: "10.6.1",
            unsupportedOSVersion: "10.14",
            form: .iMac,
            image: "https://cdsassets.apple.com/live/7WUAS350/images/imac/imac-21-5-2009-late.jpg",
            capabilities: [.usbC],
            models: ["MB950xx/A", "MC413xx/A"],
            colors: [.silverLight],
            cpu: .intel),
        Mac(
            officialName: "iMac (24-inch, Early 2009)",
            identifiers: ["iMac9,1"],
            introduction: 2009.introductionYear,
            supportId: "112427",
            launchOSVersion: "10.5.6",
            unsupportedOSVersion: "10.12",
            form: .iMac,
            image: "https://cdsassets.apple.com/live/7WUAS350/images/imac/imac-24-2009-early.jpg",
            capabilities: [.usbC],
            models: ["MB418xx/A", "MB419xx/A"],
            colors: [.silverLight],
            cpu: .intel),
        Mac(
            officialName: "iMac (20-inch, Early 2009)",
            identifiers: ["iMac9,1"],
            introduction: 2009.introductionYear,
            supportId: "112427",
            launchOSVersion: "10.5.6",
            unsupportedOSVersion: "10.12",
            form: .iMac,
            image: "https://cdsassets.apple.com/live/7WUAS350/images/imac/imac-20-2009-early.jpg",
            capabilities: [.usbC],
            models: ["MB417xx/A", "MC019xx/A"],
            colors: [.silverLight],
            cpu: .intel),

        // MARK: - MacBooks
        Mac(
            officialName: "MacBook (Retina, 12-inch, 2017)",
            identifiers: ["MacBook10,1"],
            introduction: 2017.introductionYear,
            supportId: "SP757",
            launchOSVersion: "10.12.5",
            unsupportedOSVersion: "14",
            form: .macBook,
            image: "https://cdsassets.apple.com/live/7WUAS350/images/macbook/macbook-2017-device.jpg",
            capabilities: [.usbC],
            models: ["MNYF2XX/A", "MNYG2XX/A", "MNYH2XX/A", "MNYJ2XX/A", "MNYK2XX/A", "MNYL2XX/A", "MNYM2XX/A", "MNYN2XX/A"],
            colors: [.macbookRoseGold, .macbookSpacegray, .macbookGold, .solidSilver],
            cpu: .intel),
        Mac(
            officialName: "MacBook (Retina, 12-inch, Early 2016)",
            identifiers: ["MacBook9,1"],
            introduction: 2016.introductionYear,
            supportId: "SP741",
            launchOSVersion: "10.11.4",
            unsupportedOSVersion: "13",
            form: .macBook,
            image: "https://cdsassets.apple.com/live/7WUAS350/images/macbook/macbook-2016-device.jpg",
            capabilities: [.usbC],
            models: ["MLH72xx/A", "MLH82xx/A", "MLHA2xx/A", "MLHC2xx/A", "MLHE2xx/A", "MLHF2xx/A", "MMGL2xx/A", "MMGM2xx/A"],
            colors: [.macbookRoseGold, .macbookSpacegray, .macbookGold, .solidSilver],
            cpu: .intel),
        Mac(
            officialName: "MacBook (Retina, 12-inch, Early 2015)",
            identifiers: ["MacBook8,1"],
            introduction: 2015.introductionYear,
            supportId: "SP712",
            launchOSVersion: "10.10.2",
            unsupportedOSVersion: "12",
            form: .macBook,
            image: "https://cdsassets.apple.com/live/7WUAS350/images/macbook/macbook-2015-device.jpg",
            capabilities: [.usbC],
            models: ["MF855xx/A", "MF865xx/A", "MJY32xx/A", "MJY42xx/A", "MK4M2xx/A", "MK4N2xx/A"],
            colors: [.macbookSpacegray, .macbookGold, .solidSilver],
            cpu: .intel),
        Mac(
            officialName: "MacBook (13-inch, Mid 2010)",
            identifiers: ["MacBook7,1"],
            introduction: 2010.introductionYear,
            supportId: "SP584",
            launchOSVersion: "10.6.3",
            unsupportedOSVersion: "10.14",
            form: .macBook,
            image: "https://cdsassets.apple.com/live/7WUAS350/images/macbook/macbook-late-2009-2010-device.jpg",
            capabilities: [.usbC, .magSafe1],
            models: ["MC516xx/A"],
            colors: [.white],
            cpu: .intel),
        Mac(
            officialName: "MacBook (13-inch, Late 2009)",
            identifiers: ["MacBook6,1"],
            introduction: 2009.introductionYear,
            supportId: "SP579",
            launchOSVersion: "10.6.1",
            unsupportedOSVersion: "10.14",
            form: .macBook,
            image: "https://cdsassets.apple.com/live/7WUAS350/images/macbook/macbook-late-2009-2010-device.jpg",
            capabilities: [.usbC, .magSafe1],
            models: ["MC207xx/A"],
            colors: [.white],
            cpu: .intel),
        Mac(
            officialName: "MacBook (13-inch, Mid 2009)",
            identifiers: ["MacBook5,2"],
            introduction: 2009.introductionYear,
            supportId: "SP512",
            launchOSVersion: "10.5.6",
            unsupportedOSVersion: "10.12",
            form: .macBook,
            image: "https://cdsassets.apple.com/live/7WUAS350/images/macbook/macbook-early-mid-2009-device.jpg",
            capabilities: [.usbC, .magSafe1],
            models: ["MC240xx/A"],
            colors: [.white],
            cpu: .intel),
        Mac(
            officialName: "MacBook (13-inch, Early 2009)",
            identifiers: ["MacBook5,2"],
            introduction: 2009.introductionYear,
            supportId: "SP504",
            launchOSVersion: "10.5.6",
            unsupportedOSVersion: "10.12",
            form: .macBook,
            image: "https://cdsassets.apple.com/live/7WUAS350/images/macbook/macbook-early-mid-2009-device.jpg",
            capabilities: [.usbC, .magSafe1],
            models: ["MB881xx/A"],
            colors: [.white],
            cpu: .intel),

        // MARK: - MacBook Airs
        Mac(
            officialName: "MacBook Air (15-inch, M4, 2025)",
            identifiers: ["Mac16,13"],
            introduction: 2025.introductionYear,
            supportId: "122210",
            launchOSVersion: "15.3.2", // TODO: Check for 15.3.1?
            unsupportedOSVersion: nil,
            form: .macBook,
            image: "https://cdsassets.apple.com/live/7WUAS350/images/macbook-air/2025-macbook-air-15in-colors.png",
            capabilities: [.air, .usbC, .notch],
            models: ["MC6J4xx/A", "MC6K4xx/A", "MC6L4xx/A", "MC7A4xx/A", "MC7C4xx/A", "MC7D4xx/A", "MDG34xx/A", "MDG84xx/A", "MDG94xx/A", "MW1G3xx/A", "MW1H3xx/A", "MW1J3xx/A", "MW1K3xx/A", "MW1L3xx/A", "MW1M3xx/A"],
            colors: .macbookAir2025,
            cpu: .m4),
        Mac(
            officialName: "MacBook Air (13-inch, M4, 2025)",
            identifiers: ["Mac16,12"],
            introduction: 2025.introductionYear,
            supportId: "122209",
            launchOSVersion: "15.3.2", // TODO: Check for 15.3.1?
            unsupportedOSVersion: nil,
            form: .macBookGen2,
            image: "https://cdsassets.apple.com/live/7WUAS350/images/macbook-air/2025-macbook-air-13in-colors.png",
            capabilities: [.air, .usbC, .notch],
            models: ["MC654xx/A", "MC6A4xx/A", "MC6C4xx/A", "MC6T4xx/A", "MC6U4xx/A", "MC6V4xx/A", "MDG24xx/A", "MDG54xx/A", "MDG64xx/A", "MW0W3xx/A", "MW0X3xx/A", "MW0Y3xx/A", "MW103xx/A", "MW123xx/A", "MW133xx/A"],
            colors: .macbookAir2025,
            cpu: .m4),
        Mac(
            officialName: "MacBook Air (15-inch, M3, 2024)",
            identifiers: ["Mac15,13"],
            introduction: 2024.introductionYear,
            supportId: "118552", // SP913
            launchOSVersion: "14.4",
            unsupportedOSVersion: nil,
            form: .macBookGen2,
            image: "https://cdsassets.apple.com/live/7WUAS350/images/macbook-air/2024-macbook-air-15in-m3-colors.png",
            capabilities: [.air, .usbC, .notch],
            models: ["MRYM3xx/A", "MRYP3xx/A", "MRYR3xx/A", "MRYU3xx/A", "MRYN3xx/A", "MRYQ3xx/A", "MRYT3xx/A", "MRYV3xx/A", "MXD13xx/A", "MXD23xx/A", "MXD33xx/A", "MXD43xx/A"],
            colors: [.solidSilver, .macbookairStarlight, .macbookSpacegray, .macbookairMidnight],
            cpu: .m3),
        Mac(
            officialName: "MacBook Air (13-inch, M3, 2024)",
            identifiers: ["Mac15,12"],
            introduction: 2024.introductionYear,
            supportId: "118551", // SP912
            launchOSVersion: "14.4",
            unsupportedOSVersion: nil,
            form: .macBook,
            image: "https://cdsassets.apple.com/live/7WUAS350/images/macbook-air/2024-macbook-air-13in-m3-colors.png",
            capabilities: [.air, .usbC, .notch],
            models: ["MRXN3xx/A", "MRXQ3xx/A", "MRXT3xx/A", "MRXV3xx/A", "MRXP3xx/A", "MRXR3xx/A", "MRXU3xx/A", "MRXW3xx/A", "MXCR3xx/A", "MXCT3xx/A", "MXCU3xx/A", "MXCV3xx/A"],
            colors: [.solidSilver, .macbookairStarlight, .macbookSpacegray, .macbookairMidnight],
            cpu: .m3),

        Mac(
            officialName: "MacBook Air (15-inch, M2, 2023)",
            identifiers: ["Mac14,15"],
            introduction: 2023.introductionYear,
            supportId: "111346",
            launchOSVersion: "13.4",
            unsupportedOSVersion: nil,
            form: .macBook,
            image: "https://cdsassets.apple.com/live/7WUAS350/images/macbook-air/2023-macbook-air-15in-m2-colors.png",
            capabilities: [.air, .usbC, .notch],
            models: ["MQKP3xx/A", "MQKQ3xx/A", "MQKR3xx/A", "MQKT3xx/A", "MQKU3xx/A", "MQKV3xx/A", "MQKW3xx/A", "MQKX3xx/A"],
            colors: [.solidSilver, .macbookairStarlight, .macbookSpacegray, .macbookairMidnight],
            cpu: .m2),
        Mac(
            officialName: "MacBook Air (M2, 2022)",
            identifiers: ["Mac14,2"],
            introduction: 2022.introductionYear,
            supportId: "111867",
            launchOSVersion: "12.4",
            unsupportedOSVersion: nil,
            form: .macBookGen2,
            image: "https://cdsassets.apple.com/live/7WUAS350/images/macbook-air/2022-macbook-air-m2-colors.png",
            capabilities: [.air, .usbC],
            models: ["MLXW3xx/A", "MLXX3xx/A", "MLXY3xx/A", "MLY03xx/A", "MLY13xx/A", "MLY23xx/A", "MLY33xx/A", "MLY43xx/A"],
            colors: [.solidSilver, .macbookairStarlight, .macbookSpacegray, .macbookairMidnight],
            cpu: .m2),
        Mac(
            officialName: "MacBook Air (M1, 2020)",
            identifiers: ["MacBookAir10,1"],
            introduction: 2020.introductionYear,
            supportId: "111883",
            launchOSVersion: "11.0.1",
            unsupportedOSVersion: nil,
            form: .macBook,
            image: "https://cdsassets.apple.com/live/7WUAS350/images/macbook-air/macbook-air-2020-late-device.jpg",
            capabilities: [.air, .usbC],
            models: ["MGN63xx/A", "MGN93xx/A", "MGND3xx/A", "MGN73xx/A", "MGNA3xx/A", "MGNE3xx/A"],
            colors: [.macbookSpacegray, .macbookGold, .solidSilver],
            cpu: .m1),
        Mac(
            officialName: "MacBook Air (Retina, 13-inch, 2020)",
            identifiers: ["MacBookAir9,1"],
            introduction: 2020.introductionYear,
            supportId: "111991",
            launchOSVersion: "10.15.3",
            unsupportedOSVersion: "26",
            form: .macBookGen2,
            image: "https://cdsassets.apple.com/live/7WUAS350/images/macbook-air/macbook-air-2020-device.jpg",
            capabilities: [.air, .usbC],
            models: ["MVH22xx/A", "MVH42xx/A", "MVH52xx/A", "MWTJ2xx/A", "MWTK2xx/A", "MWTL2xx/A"],
            colors: [.macbookSpacegray, .macbookGold, .solidSilver],
            cpu: .intel),
        Mac(
            officialName: "MacBook Air (Retina, 13-inch, 2019)",
            identifiers: ["MacBookAir8,2"],
            introduction: 2019.introductionYear,
            supportId: "111948",
            launchOSVersion: "10.14.5",
            unsupportedOSVersion: "15",
            form: .macBook,
            image: "https://cdsassets.apple.com/live/7WUAS350/images/macbook-air/macbook-air-2018-device.jpg",
            capabilities: [.air, .usbC],
            models: ["MVFH2xx/A", "MVFJ2xx/A", "MVFK2xx/A", "MVFL2xx/A", "MVFM2xx/A", "MVFN2xx/A", "MVH62xx/A", "MVH82xx/A"],
            colors: [.macbookSpacegray, .macbookGold, .solidSilver],
            cpu: .intel),
        Mac(
            officialName: "MacBook Air (Retina, 13-inch, 2018)",
            identifiers: ["MacBookAir8,1"],
            introduction: 2018.introductionYear,
            supportId: "111933",
            launchOSVersion: "10.14.1",
            unsupportedOSVersion: "15",
            form: .macBook, // USB-C only charging, no mag-safe
            image: "https://cdsassets.apple.com/live/7WUAS350/images/macbook-air/macbook-air-2018-device.jpg",
            capabilities: [.air, .usbC],
            models: ["MRE82xx/A", "MREA2xx/A", "MREE2xx/A", "MRE92xx/A", "MREC2xx/A", "MREF2xx/A", "MUQT2xx/A", "MUQU2xx/A", "MUQV2xx/A"],
            colors: [.macbookSpacegray, .macbookGold, .solidSilver],
            cpu: .intel),
        Mac(
            officialName: "MacBook Air (13-inch, 2017)",
            identifiers: ["MacBookAir7,2"],
            introduction: 2017.introductionYear,
            supportId: "111924",
            launchOSVersion: "10.10.2",
            unsupportedOSVersion: "13",
            form: .macBookGen1,
            image: "https://cdsassets.apple.com/live/7WUAS350/images/macbook-air/macbook-air-2017-device.jpg",
            capabilities: [.air, .usbC],
            models: ["MQD32xx/A", "MQD42xx/A", "MQD52xx/A"],
            colors: .legacySilverMacs,
            cpu: .intel),
        Mac(
            officialName: "MacBook Air (13-inch, Early 2015)",
            identifiers: ["MacBookAir7,2"],
            introduction: 2015.introductionYear,
            supportId: "111956",
            launchOSVersion: "10.10.2",
            unsupportedOSVersion: "13",
            form: .macBookGen1,
            image: "https://cdsassets.apple.com/live/7WUAS350/images/macbook-air/macbook-air-2015-13in-device.jpg",
            capabilities: [.air, .usbC],
            models: ["MJVE2xx/A", "MJVG2xx/A", "MMGF2xx/A", "MMGG2xx/A"],
            colors: .legacySilverMacs,
            cpu: .intel),
        Mac(
            officialName: "MacBook Air (11-inch, Early 2015)",
            identifiers: ["MacBookAir7,1"],
            introduction: 2015.introductionYear,
            supportId: "112441",
            launchOSVersion: "10.10.2",
            unsupportedOSVersion: "13",
            form: .macBookGen1,
            image: "https://cdsassets.apple.com/live/7WUAS350/images/macbook-air/macbook-air-2015-11in-device.jpg",
            capabilities: [.air, .usbC],
            models: ["MJVM2xx/A", "MJVP2xx/A"],
            colors: .legacySilverMacs,
            cpu: .intel),
        Mac(
            officialName: "MacBook Air (13-inch, Early 2014)",
            identifiers: ["MacBookAir6,2"],
            introduction: 2014.introductionYear,
            supportId: "111944",
            launchOSVersion: "10.9.2",
            unsupportedOSVersion: "12",
            form: .macBookGen1,
            image: "https://cdsassets.apple.com/live/7WUAS350/images/macbook-air/macbook-air-2013-2014-13in-device.jpg",
            capabilities: [.air, .usbC],
            models: ["MD760xx/B", "MD761xx/B"],
            colors: .legacySilverMacs,
            cpu: .intel),
        Mac(
            officialName: "MacBook Air (11-inch, Early 2014)",
            identifiers: ["MacBookAir6,1"],
            introduction: 2014.introductionYear,
            supportId: "112032",
            launchOSVersion: "10.9.2",
            unsupportedOSVersion: "12",
            form: .macBookGen1,
            image: "https://cdsassets.apple.com/live/7WUAS350/images/macbook-air/macbook-air-2013-2014-11in-device.jpg",
            capabilities: [.air, .usbC],
            models: ["MD711xx/B", "MD712xx/B"],
            colors: .legacySilverMacs,
            cpu: .intel),
        Mac(
            officialName: "MacBook Air (13-inch, Mid 2013)",
            identifiers: ["MacBookAir6,2"],
            introduction: 2013.introductionYear,
            supportId: "111938",
            launchOSVersion: "10.8.4",
            unsupportedOSVersion: "12",
            form: .macBookGen1,
            image: "https://cdsassets.apple.com/live/7WUAS350/images/macbook-air/macbook-air-2013-2014-13in-device.jpg",
            capabilities: [.air, .usbC],
            models: ["MD760xx/A", "MD761xx/A"],
            colors: .legacySilverMacs,
            cpu: .intel),
        Mac(
            officialName: "MacBook Air (11-inch, Mid 2013)",
            identifiers: ["MacBookAir6,1"],
            introduction: 2013.introductionYear,
            supportId: "112437",
            launchOSVersion: "10.9.2",
            unsupportedOSVersion: "12",
            form: .macBook,
            image: "https://cdsassets.apple.com/live/7WUAS350/images/macbook-air/macbook-air-2013-2014-11in-device.jpg",
            capabilities: [.air, .usbC],
            models: ["MD711xx/A", "MD712xx/A"],
            colors: .legacySilverMacs,
            cpu: .intel),
        Mac(
            officialName: "MacBook Air (13-inch, Mid 2012)",
            identifiers: ["MacBookAir5,2"],
            introduction: 2012.introductionYear,
            supportId: "111966",
            launchOSVersion: "10.8.2",
            unsupportedOSVersion: "11",
            form: .macBook,
            image: "https://cdsassets.apple.com/live/7WUAS350/images/macbook-air/macbook-air-2012-13in-device.jpg",
            capabilities: [.air, .usbC],
            models: ["MD231xx/A", "MD232xx/A"],
            colors: .legacySilverMacs,
            cpu: .intel),
        Mac(
            officialName: "MacBook Air (11-inch, Mid 2012)",
            identifiers: ["MacBookAir5,1"],
            introduction: 2012.introductionYear,
            supportId: "112008",
            launchOSVersion: "10.7.4",
            unsupportedOSVersion: "11",
            form: .macBook,
            image: "https://cdsassets.apple.com/live/7WUAS350/images/macbook-air/macbook-air-2012-11in-device.jpg",
            capabilities: [.air, .usbC],
            models: ["MD223xx/A", "MD224xx/A"],
            colors: .legacySilverMacs,
            cpu: .intel),
        Mac(
            officialName: "MacBook Air (13-inch, Mid 2011)",
            identifiers: ["MacBookAir4,2"],
            introduction: 2011.introductionYear,
            supportId: "112038",
            launchOSVersion: "10.7",
            unsupportedOSVersion: "10.14",
            form: .macBook,
            image: "https://cdsassets.apple.com/live/7WUAS350/images/macbook-air/macbook-air-2011-13in-device.jpg",
            capabilities: [.air, .usbC],
            models: ["MC965xx/A", "MC966xx/A"],
            colors: .legacySilverMacs,
            cpu: .intel),
        Mac(
            officialName: "MacBook Air (11-inch, Mid 2011)",
            identifiers: ["MacBookAir4,1"],
            introduction: 2011.introductionYear,
            supportId: "112439",
            launchOSVersion: "10.7",
            unsupportedOSVersion: "10.14",
            form: .macBook,
            image: "https://cdsassets.apple.com/live/7WUAS350/images/macbook-air/macbook-air-2011-11in-device.jpg",
            capabilities: [.air, .usbC],
            models: ["MC968xx/A", "MC969xx/A"],
            colors: .legacySilverMacs,
            cpu: .intel),
        Mac(
            officialName: "MacBook Air (13-inch, Late 2010)",
            identifiers: ["MacBookAir3,2"],
            introduction: 2010.introductionYear,
            supportId: "112585",
            launchOSVersion: "10.6.4",
            unsupportedOSVersion: "10.14",
            form: .macBook,
            image: "https://cdsassets.apple.com/live/7WUAS350/images/macbook-air/macbook-air-2009-2010-13in-device.jpg",
            capabilities: [.air, .usbC],
            models: ["MC503xx/A", "MC504xx/A"],
            colors: .legacySilverMacs,
            cpu: .intel),
        Mac(
            officialName: "MacBook Air (11-inch, Late 2010)",
            identifiers: ["MacBookAir3,1"],
            introduction: 2010.introductionYear,
            supportId: "112580",
            launchOSVersion: "10.6.4",
            unsupportedOSVersion: "10.14",
            form: .macBook,
            image: "https://cdsassets.apple.com/live/7WUAS350/images/macbook-air/macbook-air-2010-11in-device.jpg",
            capabilities: [.air, .usbC],
            models: ["MC505xx/A", "MC506xx/A"],
            colors: .legacySilverMacs,
            cpu: .intel),
        Mac(
            officialName: "MacBook Air (Mid 2009)",
            identifiers: ["MacBookAir2,1"],
            introduction: 2009.introductionYear,
            supportId: "112660",
            launchOSVersion: "10.5.7",
            unsupportedOSVersion: "10.12",
            form: .macBook,
            image: "https://cdsassets.apple.com/live/7WUAS350/images/macbook-air/macbook-air-2009-2010-13in-device.jpg",
            capabilities: [.air, .usbC],
            models: ["MC505xx/A", "MC233xx/A", "MC234xx/A"],
            colors: .legacySilverMacs,
            cpu: .intel),
        
        // MARK: - MacBook Pros
        Mac(
            officialName: "MacBook Pro (14-inch, 2024) M4",
            identifiers: ["Mac16,1"],
            introduction: "2024-10-30",
            supportId: "121552",
            launchOSVersion: "15",
            unsupportedOSVersion: nil,
            form: .macBookGen2,
            image: "https://cdsassets.apple.com/live/7WUAS350/images/macbook-pro/macbook-pro-14in-2024-m4-colors.png",
            capabilities: [.pro],
            models: ["MCX04xx/A", "MCX14xx/A", "MW2U3xx/A", "MW2V3xx/A", "MW2W3xx/A", "MW2X3xx/A", "MXCM3xx/A", "MXCN3xx/A"],
            colors: [.solidSilver, .macbookSpacegray],
            cpu: .m4,
            screen: Screen(diagonal: 14.2, resolution: (3024,1964), ppi: 254)),
        Mac(
            officialName: "MacBook Pro (14-inch, 2024) M4 Pro",
            identifiers: ["Mac16,6"],
            introduction: "2024-10-30",
            supportId: "121553",
            launchOSVersion: "15",
            unsupportedOSVersion: nil,
            form: .macBookGen2,
            image: "https://cdsassets.apple.com/live/7WUAS350/images/macbook-pro/macbook-pro-14in-2024-m4-pro-m4-max-colors.png",
            capabilities: [.pro],
            models: ["MXE63xx/A", "MX2E3xx/A", "MX2F3xx/A", "MX2G3xx/A", "MX2H3xx/A", "MX2J3xx/A", "MX2K3xx/A"],
            colors: [.solidSilver, .macbookSpacegray],
            cpu: .m4pro,
            screen: Screen(diagonal: 14.2, resolution: (3024,1964), ppi: 254)),
        Mac(
            officialName: "MacBook Pro (14-inch, 2024) M4 Max",
            identifiers: ["Mac16,8"],
            introduction: "2024-10-30",
            supportId: "121553",
            launchOSVersion: "15",
            unsupportedOSVersion: nil,
            form: .macBookGen2,
            image: "https://cdsassets.apple.com/live/7WUAS350/images/macbook-pro/macbook-pro-14in-2024-m4-pro-m4-max-colors.png",
            capabilities: [.pro],
            models: ["MXE63xx/A", "MX2E3xx/A", "MX2F3xx/A", "MX2G3xx/A", "MX2H3xx/A", "MX2J3xx/A", "MX2K3xx/A"],
            colors: [.solidSilver, .macbookSpacegray],
            cpu: .m4max,
            screen: Screen(diagonal: 14.2, resolution: (3024,1964), ppi: 254)),
        Mac(
            officialName: "MacBook Pro (16-inch, 2024) M4 Max",
            identifiers: ["Mac16,7"],
            introduction: "2024-10-30",
            supportId: "121554",
            launchOSVersion: "15",
            unsupportedOSVersion: nil,
            form: .macBookGen2,
            image: "https://cdsassets.apple.com/live/7WUAS350/images/macbook-pro/macbook-pro-16in-2024-colors.png",
            capabilities: [.pro],
            models: ["MX2T3xx/A", "MX2U3xx/A", "MX2W3xx/A", "MX2X3xx/A", "MX2Y3xx/A", "MX313xx/A"],
            colors: [.solidSilver, .macbookSpacegray],
            cpu: .m4max,
            screen: Screen(diagonal: 16.2, resolution: (3456,2234), ppi: 254)),
        Mac(
            officialName: "MacBook Pro (16-inch, 2024) M4 Pro",
            identifiers: ["Mac16,5"],
            introduction: "2024-10-30",
            supportId: "121554",
            launchOSVersion: "15",
            unsupportedOSVersion: nil,
            form: .macBookGen2,
            image: "https://cdsassets.apple.com/live/7WUAS350/images/macbook-pro/macbook-pro-16in-2024-colors.png",
            capabilities: [.pro],
            models: ["MX2V3xx/A", "MX303xx/A"],
            colors: [.solidSilver, .macbookSpacegray],
            cpu: .m4pro,
            screen: Screen(diagonal: 16.2, resolution: (3456,2234), ppi: 254)),
        Mac(
            officialName: "MacBook Pro (14-inch, 2023)",
            identifiers: ["Mac14,5", "Mac14,9"],
            introduction: "2023-01-17",
            supportId: "111340", // SP889
            launchOSVersion: "13.2",
            unsupportedOSVersion: nil,
            form: .macBookGen2,
            image: "https://cdsassets.apple.com/live/7WUAS350/images/macbook-pro/macbook-pro-14in-2023.png",
            capabilities: [.pro],
            models: ["MPHE3xx/A", "MPHF3xx/A", "MPHG3xx/A", "MPHH3xx/A", "MPHJ3xx/A", "MPHK3xx/A"],
            colors: [.solidSilver, .macbookSpacegray],
            cpu: .m2pro),
        Mac(
            officialName: "MacBook Pro (16-inch, 2023)",
            identifiers: ["Mac14,6", "Mac14,10"],
            introduction: "2023-01-17",
            supportId: "111838", // SP890
            launchOSVersion: "13.2",
            unsupportedOSVersion: nil,
            form: .macBookGen2,
            image: "https://cdsassets.apple.com/live/7WUAS350/images/macbook-pro/macbook-pro-16in-2023.png",
            capabilities: [.pro],
            models: ["MNWG3xx/A", "MNW93xx/A", "MNWK3xx/A", "MNWD3xx/A", "MNWF3xx/A", "MNW83xx/A", "MNWJ3xx/A", "MNWC3xx/A"],
            colors: [.solidSilver, .macbookSpacegray],
            cpu: .m2pro,
            screen: Screen(diagonal: 16.2, resolution: (3456,2234), ppi: 254)),
        Mac(
            officialName: "MacBook Pro (14-inch, Nov 2023) M3",
            identifiers: ["Mac15,3"],
            introduction: "2023-10-30",
            supportId: "117735", // SP890
            launchOSVersion: "14.1",
            unsupportedOSVersion: nil,
            form: .macBookGen2,
            image: "https://cdsassets.apple.com/live/7WUAS350/images/macbook-pro/macbook-pro-14in-m3-nov-2023-silver-space-gray.png",
            capabilities: [.pro],
            models: ["MR7J3xx/A", "MR7K3xx/A", "MRX23xx/A", "MTL73xx/A", "MTL83xx/A", "MTLC3xx/A", "MXE03xx/A", "MXE13xx/A"],
            colors: [.solidSilver, .macbookSpacegray],
            cpu: .m3,
            screen: Screen(diagonal: 14.2, resolution: (3024,1964), ppi: 254)),
        Mac(
            officialName: "MacBook Pro (14-inch, Nov 2023) M3 Pro",
            identifiers: ["Mac15,6"],
            introduction: "2023-10-30",
            supportId: "117736",
            launchOSVersion: "14.1",
            unsupportedOSVersion: nil,
            form: .macBookGen2,
            image: "https://cdsassets.apple.com/live/7WUAS350/images/macbook-pro/macbook-pro-14in-m3-pro-m3-max-nov-2023-silver-space-black.png",
            capabilities: [.pro],
            models: ["FRX33xx/A", "FRX43xx/A", "FRX54xx/A", "FRX63xx/A", "FRX73xx/A", "FRX83xx/A", "MRX33xx/A", "MRX43xx/A", "MRX53xx/A", "MRX63xx/A", "MRX73xx/A", "MRX83xx/A"],
            colors: [.solidSilver, .macbookSpacegray],
            cpu: .m3pro,
            screen: Screen(diagonal: 14.2, resolution: (3024,1964), ppi: 254)),
        Mac(
            officialName: "MacBook Pro (14-inch, Nov 2023) M3 Max",
            identifiers: ["Mac15,8", "Mac15,10"],
            introduction: "2023-10-30",
            supportId: "117736", // #max
            launchOSVersion: "14.1",
            unsupportedOSVersion: nil,
            form: .macBookGen2,
            image: "https://cdsassets.apple.com/live/7WUAS350/images/macbook-pro/macbook-pro-14in-m3-pro-m3-max-nov-2023-silver-space-black.png",
            capabilities: [.pro],
            models: ["FRX33xx/A", "FRX43xx/A", "FRX54xx/A", "FRX63xx/A", "FRX73xx/A", "FRX83xx/A", "MRX33xx/A", "MRX43xx/A", "MRX53xx/A", "MRX63xx/A", "MRX73xx/A", "MRX83xx/A"],
            colors: [.solidSilver, .macbookSpacegray],
            cpu: .m3max,
            screen: Screen(diagonal: 14.2, resolution: (3024,1964), ppi: 254)),
        Mac(
            officialName: "MacBook Pro (16-inch, Nov 2023) M3 Pro",
            identifiers: ["Mac15,7"],
            introduction: "2023-10-30",
            supportId: "117737",
            launchOSVersion: "14.1",
            unsupportedOSVersion: nil,
            form: .macBookGen2,
            image: "https://cdsassets.apple.com/live/7WUAS350/images/macbook-pro/macbook-pro-16in-m3-pro-m3-max-nov-2023-silver-space-black.png",
            capabilities: [.pro],
            models: ["FRW13xx/A", "FRW23xx/A", "FRW33xx/A", "FRW43xx/A", "FRW63xx/A", "FRW73xx/A", "FUW63xx/A", "FUW73xx/A", "MRW13xx/A", "MRW23xx/A", "MRW33xx/A", "MRW43xx/A", "MRW63xx/A", "MRW73xx/A"],
            colors: [.solidSilver, .macbookSpacegray],
            cpu: .m3pro,
            screen: Screen(diagonal: 16.2, resolution: (3456,2234), ppi: 254)),
        Mac(
            officialName: "MacBook Pro (16-inch, Nov 2023) M3 Max",
            identifiers: ["Mac15,9", "Mac15,11"],
            introduction: "2023-10-30",
            supportId: "117737", // #Max
            launchOSVersion: "14.1",
            unsupportedOSVersion: nil,
            form: .macBookGen2,
            image: "https://cdsassets.apple.com/live/7WUAS350/images/macbook-pro/macbook-pro-16in-m3-pro-m3-max-nov-2023-silver-space-black.png?",
            capabilities: [.pro],
            models: ["FRW13xx/A", "FRW23xx/A", "FRW33xx/A", "FRW43xx/A", "FRW63xx/A", "FRW73xx/A", "FUW63xx/A", "FUW73xx/A", "MRW13xx/A", "MRW23xx/A", "MRW33xx/A", "MRW43xx/A", "MRW63xx/A", "MRW73xx/A"],
            colors: [.solidSilver, .macbookSpacegray],
            cpu: .m3max,
            screen: Screen(diagonal: 16.2, resolution: (3456,2234), ppi: 254)),
        Mac(
            officialName: "MacBook Pro (13-inch, M2, 2022)",
            identifiers: ["Mac14,7"],
            introduction: "2022-06-06",
            supportId: "111869",
            launchOSVersion: "12.4",
            unsupportedOSVersion: nil,
            form: .macBook,
            image: "https://cdsassets.apple.com/live/7WUAS350/images/macbook-pro/macbook-pro-13-in-M2-2022.png",
            capabilities: [.pro],
            models: ["MNEH3xx/A", "MNEJ3xx/A", "MNEP3xx/A", "MNEQ3xx/A"],
            colors: [.solidSilver, .macbookSpacegray],
            cpu: .m2),
        Mac(
            officialName: "MacBook Pro (14-inch, 2021)",
            identifiers: ["MacBookPro18,3", "MacBookPro18,4"],
            introduction: 2021.introductionYear,
            supportId: "111902",
            launchOSVersion: "12.0.1",
            unsupportedOSVersion: nil,
            form: .macBook,
            image: "https://cdsassets.apple.com/live/7WUAS350/images/macbook-pro/macbook-pro-2021-14in.png",
            capabilities: [.pro],
            models: ["MKGP3xx/A", "MKGQ3xx/A", "MKGR3xx/A", "MKGT3xx/A"],
            colors: [.solidSilver, .macbookSpacegray],
            cpu: .intel),
        Mac(
            officialName: "MacBook Pro (16-inch, 2021)",
            identifiers: ["MacBookPro18,1", "MacBookPro18,2"],
            introduction: 2021.introductionYear,
            supportId: "111901",
            launchOSVersion: "12.0.1",
            unsupportedOSVersion: nil,
            form: .macBookGen2,
            image: "https://cdsassets.apple.com/live/7WUAS350/images/macbook-pro/macbook-pro-2021-16in.png",
            capabilities: [.pro],
            models: ["MK183xx/A", "MK193xx/A", "MK1A3xx/A", "MK1E3xx/A", "MK1F3xx/A", "MK1H3xx/A"],
            colors: [.solidSilver, .macbookSpacegray],
            cpu: .intel),
        Mac(
            officialName: "MacBook Pro (13-inch, M1, 2020)",
            identifiers: ["MacBookPro17,1"],
            introduction: 2020.introductionYear,
            supportId: "111893",
            launchOSVersion: "11.0.1",
            unsupportedOSVersion: nil,
            form: .macBook,
            image: "https://cdsassets.apple.com/live/7WUAS350/images/macbook-pro/macbook-pro-2020-late-13in-device.jpg",
            capabilities: [.pro, .usbC, .biometrics(.touchID)],
            models: ["MYD83xx/A", "MYD92xx/A", "MYDA2xx/A", "MYDC2xx/A"],
            colors: [.solidSilver, .macbookSpacegray],
            cpu: .m1),
        Mac(
            officialName: "MacBook Pro (13-inch, 2020, Two Thunderbolt 3 ports)",
            identifiers: ["MacBookPro16,3"],
            introduction: 2020.introductionYear,
            supportId: "111981",
            launchOSVersion: "10.15.4",
            unsupportedOSVersion: "26",
            form: .macBook,
            image: "https://cdsassets.apple.com/live/7WUAS350/images/macbook-pro/macbook-pro-2020-13in-device-3.jpg",
            capabilities: [.pro, .usbC, .thunderbolt, .biometrics(.touchID)],
            models: ["MXK32xx/A", "MXK52xx/A", "MXK62xx/A", "MXK72xx/A"],
            colors: [.solidSilver, .macbookSpacegray],
            cpu: .intel),
        Mac(
            officialName: "MacBook Pro (13-inch, 2020, Four Thunderbolt 3 ports)",
            identifiers: ["MacBookPro16,2"],
            introduction: 2020.introductionYear,
            supportId: "111339",
            launchOSVersion: "10.15.4",
            unsupportedOSVersion: nil,
            form: .macBook,
            image: "https://cdsassets.apple.com/live/7WUAS350/images/macbook-pro/macbook-pro-2020-13in-device-3.jpg",
            capabilities: [.pro, .usbC, .thunderbolt, .biometrics(.touchID)],
            models: ["MWP42xx/A", "MWP52xx/A", "MWP62xx/A", "MWP72xx/A", "MWP82xx/A"],
            colors: [.solidSilver, .macbookSpacegray],
            cpu: .intel),
        Mac(
            officialName: "MacBook Pro (16-inch, 2019)",
            identifiers: ["MacBookPro16,1", "MacBookPro16,4"],
            introduction: 2019.introductionYear,
            supportId: "111932",
            launchOSVersion: "10.15.1",
            unsupportedOSVersion: nil,
            form: .macBook,
            image: "https://cdsassets.apple.com/live/7WUAS350/images/macbook-pro/macbook-pro-16in-2019.jpg",
            capabilities: [.pro, .usbC, .biometrics(.touchID)],
            models: ["MVVJ2xx/A", "MVVK2xx/A", "MVVL2xx/A", "MVVM2xx/A"],
            colors: [.solidSilver, .macbookSpacegray],
            cpu: .intel),
        Mac(
            officialName: "MacBook Pro (13-inch, 2019, Two Thunderbolt 3 ports)",
            identifiers: ["MacBookPro15,4"],
            introduction: 2019.introductionYear,
            supportId: "111945", // SP799
            launchOSVersion: "10.14.5",
            unsupportedOSVersion: "26",
            form: .macBook,
            image: "https://cdsassets.apple.com/live/7WUAS350/images/macbook-pro/macbook-pro-2018-13in-device.jpg",
            capabilities: [.pro, .usbC, .thunderbolt, .biometrics(.touchID)],
            models: ["MUHN2xx/A", "MUHP2xx/a", "MUHQ2xx/A", "MUHR2xx/A", "MUHR2xx/B"],
            colors: [.solidSilver, .macbookSpacegray],
            cpu: .intel),
        Mac(
            officialName: "MacBook Pro (15-inch, 2019)",
            identifiers: ["MacBookPro15,1", "MacBookPro15,3"],
            introduction: 2019.introductionYear,
            supportId: "111941",
            launchOSVersion: "10.13.6",
            unsupportedOSVersion: "26",
            form: .macBook,
            image: "https://cdsassets.apple.com/live/7WUAS350/images/macbook-pro/macbook-pro-2018-15in-device-2.jpg",
            capabilities: [.pro, .usbC, .biometrics(.touchID)],
            models: ["MV902xx/A", "MV912xx/A", "MV922xx/A", "MV932xx/A", "MV942xx/A", "MV952xx/A"],
            colors: [.solidSilver, .macbookSpacegray],
            cpu: .intel),
        Mac(
            officialName: "MacBook Pro (13-inch, 2019, Four Thunderbolt 3 ports)",
            identifiers: ["MacBookPro15,2"],
            introduction: 2019.introductionYear,
            supportId: "111997",
            launchOSVersion: "10.13.6",
            unsupportedOSVersion: "26",
            form: .macBook,
            image: "https://cdsassets.apple.com/live/7WUAS350/images/macbook-pro/macbook-pro-2018-13in-device.jpg",
            capabilities: [.pro, .usbC, .thunderbolt, .biometrics(.touchID)],
            models: ["MV962xx/A", "MV972xx/A", "MV982xx/A", "MV992xx/A", "MV9A2xx/A"],
            colors: [.solidSilver, .macbookSpacegray],
            cpu: .intel),
        Mac(
            officialName: "MacBook Pro (15-inch, 2018)",
            identifiers: ["MacBookPro15,1"],
            introduction: "2018-07-12",
            supportId: "111949",
            launchOSVersion: "10.13.6",
            unsupportedOSVersion: "26",
            form: .macBook,
            image: "https://cdsassets.apple.com/live/7WUAS350/images/macbook-pro/macbook-pro-2018-15in-device-2.jpg",
            capabilities: [.pro, .usbC],
            models: ["MR932xx/A", "MR942xx/A", "MR952xx/A", "MR962xx/A", "MR972xx/A", "MUQH2xx/A"],
            colors: [.solidSilver, .macbookSpacegray],
            cpu: .intel),
        Mac(
            officialName: "MacBook Pro (13-inch, 2018, Four Thunderbolt 3 ports)",
            identifiers: ["MacBookPro15,2"],
            introduction: "2018-07-12",
            supportId: "111925",
            launchOSVersion: "10.13.6",
            unsupportedOSVersion: "26",
            form: .macBook,
            image: "https://cdsassets.apple.com/live/7WUAS350/images/macbook-pro/macbook-pro-2018-13in-device.jpg",
            capabilities: [.pro, .usbC, .thunderbolt],
            models: ["MR9Q2xx/A", "MR9R2xx/A", "MR9T2xx/A", "MR9U2xx/A", "MR9V2xx/A"],
            colors: [.solidSilver, .macbookSpacegray],
            cpu: .intel),
        Mac(
            officialName: "MacBook Pro (15-inch, 2017)",
            identifiers: ["MacBookPro14,3"],
            introduction: "2017-06-05",
            supportId: "111947",
            launchOSVersion: "10.12.5",
            unsupportedOSVersion: "14",
            form: .macBook,
            image: "https://cdsassets.apple.com/live/7WUAS350/images/macbook-pro/macbook-pro-2017-15in-device.jpg",
            capabilities: [.pro, .usbC, .biometrics(.touchID)],
            models: ["MPTR2xx/A", "MPTT2xx/A", "MPTU2xx/A", "MPTV2xx/A", "MPTW2xx/A", "MPTX2xx/A"],
            colors: [.solidSilver, .macbookSpacegray],
            cpu: .intel),
        Mac(
            officialName: "MacBook Pro (13-inch, 2017, Four Thunderbolt 3 ports)",
            identifiers: ["MacBookPro14,2"],
            introduction: "2017-06-05",
            supportId: "111972",
            launchOSVersion: "10.12.5",
            unsupportedOSVersion: "14",
            form: .macBook,
            image: "https://cdsassets.apple.com/live/7WUAS350/images/macbook-pro/macbook-pro-2017-13in-device.jpg",
            capabilities: [.pro, .usbC, .thunderbolt, .biometrics(.touchID)],
            models: ["MPXV2xx/A", "MPXW2xx/A", "MPXX2xx/A", "MPXY2xx/A", "MQ002xx/A", "MQ012xx/A"],
            colors: [.solidSilver, .macbookSpacegray],
            cpu: .intel),
        Mac(
            officialName: "MacBook Pro (13-inch, 2017, Two Thunderbolt 3 ports)",
            identifiers: ["MacBookPro14,1"],
            introduction: "2017-06-05",
            supportId: "111951",
            launchOSVersion: "10.12.5",
            unsupportedOSVersion: "14",
            form: .macBook,
            image: "https://cdsassets.apple.com/live/7WUAS350/images/macbook-pro/macbook-pro-2017-13in-device-2thunderbolt-3ports.jpg",
            capabilities: [.pro, .usbC, .thunderbolt],
            models: ["MPXQ2xx/A", "MPXR2xx/A", "MPXT2xx/A", "MPXU2xx/A"],
            colors: [.solidSilver, .macbookSpacegray],
            cpu: .intel),
        Mac(
            officialName: "MacBook Pro (15-inch, 2016)", // Touchbook, macOS 12
            identifiers: ["MacBookPro13,3"],
            introduction: 2016.introductionYear,
            supportId: "111975",
            launchOSVersion: "10.12.1",
            unsupportedOSVersion: "13",
            form: .macBook,
            image: "https://cdsassets.apple.com/live/7WUAS350/images/macbook-pro/macbook-pro-2016-15in-device.jpg",
            capabilities: [.pro, .usbC, .biometrics(.touchID)],
            models: ["MLH32xx/A", "MLH42xx/A", "MLH52xx/A", "MLW72xx/A", "MLW82xx/A", "MLW92xx/A"],
            colors: [.solidSilver, .macbookSpacegray],
            cpu: .intel),
        Mac(
            officialName: "MacBook Pro (13-inch, 2016, Four Thunderbolt 3 ports)",
            identifiers: ["MacBookPro13,2"],
            introduction: 2016.introductionYear,
            supportId: "112003",
            launchOSVersion: "10.12.1",
            unsupportedOSVersion: "13",
            form: .macBook,
            image: "https://cdsassets.apple.com/live/7WUAS350/images/macbook-pro/macbook-pro-2016-13in-device.jpg",
            capabilities: [.pro, .usbC, .thunderbolt, .biometrics(.touchID)],
            models: ["MLH12xx/A", "MLVP2xx/A", "MNQF2xx/A", "MNQG2xx/A", "MPDK2xx/A", "MPDL2xx/A"],
            colors: [.solidSilver, .macbookSpacegray],
            cpu: .intel),
        Mac(
            officialName: "MacBook Pro (13-inch, 2016, Two Thunderbolt 3 ports)",
            identifiers: ["MacBookPro13,1"],
            introduction: 2016.introductionYear,
            supportId: "111999",
            launchOSVersion: "10.12",
            unsupportedOSVersion: "13",
            form: .macBook,
            image: "https://cdsassets.apple.com/live/7WUAS350/images/macbook-pro/macbook-pro-2016-13in-device.jpg",
            capabilities: [.pro, .usbC, .thunderbolt],
            models: ["MLL42xx/A", "MLUQ2xx/A"],
            colors: [.solidSilver, .macbookSpacegray],
            cpu: .intel),
        Mac(
            officialName: "MacBook Pro (Retina, 15-inch, Mid 2015)",
            identifiers: ["MacBookPro11,4", "MacBookPro11,5"],
            introduction: 2015.introductionYear,
            supportId: "111955",
            launchOSVersion: "10.10.3",
            unsupportedOSVersion: "13",
            form: .macBookGen1,
            image: "https://cdsassets.apple.com/live/7WUAS350/images/macbook-pro/macbook-pro-mid-2015-15in-device.jpg",
            capabilities: [.pro, .usbC],
            models: ["MJLQ2xx/A", "MJLT2xx/A", "MJLU2xx/A"],
            colors: .legacySilverMacs,
            cpu: .intel),
        Mac(
            officialName: "MacBook Pro (Retina, 13-inch, Early 2015)",
            identifiers: ["MacBookPro12,1"],
            introduction: 2015.introductionYear,
            supportId: "111959",
            launchOSVersion: "10.10.2",
            unsupportedOSVersion: "13",
            form: .macBook,
            image: "https://cdsassets.apple.com/live/7WUAS350/images/macbook-pro/macbook-pro-early-2015-13in-device.jpg",
            capabilities: [.pro, .usbC],
            models: ["MF839xx/A", "MF840xx/A", "MF841xx/A", "MF843xx/A"],
            colors: .legacySilverMacs,
            cpu: .intel),
        Mac(
            officialName: "MacBook Pro (Retina, 15-inch, Mid 2014)",
            identifiers: ["MacBookPro11,2", "MacBookPro11,3"],
            introduction: 2014.introductionYear,
            supportId: "111935",
            launchOSVersion: "10.9",
            unsupportedOSVersion: "12",
            form: .macBook,
            image: "https://cdsassets.apple.com/live/7WUAS350/images/macbook-pro/macbook-pro-mid-2014-15in-device.jpg",
            capabilities: [.pro, .usbC],
            models: ["MGXC2xx/A", "MGXA2xx/A"],
            colors: .legacySilverMacs,
            cpu: .intel),
        Mac(
            officialName: "MacBook Pro (Retina, 13-inch, Mid 2014)",
            identifiers: ["MacBookPro11,1"],
            introduction: 2014.introductionYear,
            supportId: "111942",
            launchOSVersion: "10.9",
            unsupportedOSVersion: "12",
            form: .macBook,
            image: "https://cdsassets.apple.com/live/7WUAS350/images/macbook-pro/macbook-pro-mid-2014-13in-device.jpg",
            capabilities: [.pro, .usbC],
            models: ["MGX72xx/A", "MGX82xx/A", "MGX92xx/A"],
            colors: .legacySilverMacs,
            cpu: .intel),
        Mac(
            officialName: "MacBook Pro (Retina, 15-inch, Late 2013)",
            identifiers: ["MacBookPro11,2", "MacBookPro11,3"],
            introduction: 2013.introductionYear,
            supportId: "111971",
            launchOSVersion: "10.9",
            unsupportedOSVersion: "12",
            form: .macBook,
            image: "https://cdsassets.apple.com/live/7WUAS350/images/macbook-pro/macbook-pro-late-2013-15in-device.jpg",
            capabilities: [.pro, .usbC],
            models: ["ME293xx/A", "ME294xx/A"],
            colors: .legacySilverMacs,
            cpu: .intel),
        Mac(
            officialName: "MacBook Pro (Retina, 13-inch, Late 2013)",
            identifiers: ["MacBookPro11,1"],
            introduction: 2013.introductionYear,
            supportId: "111946",
            launchOSVersion: "10.9",
            unsupportedOSVersion: "12",
            form: .macBook,
            image: "https://cdsassets.apple.com/live/7WUAS350/images/macbook-pro/macbook-pro-late-2013-13in-device.jpg",
            capabilities: [.pro, .usbC],
            models: ["ME864xx/A", "ME865xx/A", "ME866xx/A"],
            colors: .legacySilverMacs,
            cpu: .intel),
        Mac(
            officialName: "MacBook Pro (Retina, 15-inch, Early 2013)",
            identifiers: ["MacBookPro10,1"],
            introduction: 2013.introductionYear,
            supportId: "118465",
            launchOSVersion: "10.7.4",
            unsupportedOSVersion: "11",
            form: .macBook,
            image: "https://cdsassets.apple.com/live/7WUAS350/images/macbook-pro/macbook-pro-early-2013-15in-device.jpg",
            capabilities: [.pro, .usbC],
            models: ["ME664xx/A", "ME665xx/A"],
            colors: .legacySilverMacs,
            cpu: .intel),
        Mac(
            officialName: "MacBook Pro (Retina, 13-inch, Early 2013)",
            identifiers: ["MacBookPro10,2"],
            introduction: 2013.introductionYear,
            supportId: "118466",
            launchOSVersion: "10.8.2",
            unsupportedOSVersion: "11",
            form: .macBook,
            image: "https://cdsassets.apple.com/live/7WUAS350/images/macbook-pro/macbook-pro-early-2013-13in-device.jpg",
            capabilities: [.pro, .usbC],
            models: ["MD212xx/A", "ME662xx/A"],
            colors: .legacySilverMacs,
            cpu: .intel),
        Mac(
            officialName: "MacBook Pro (Retina, 13-inch, Late 2012)",
            identifiers: ["MacBookPro10,2"],
            introduction: 2012.introductionYear,
            supportId: "118463",
            launchOSVersion: "10.8.2",
            unsupportedOSVersion: "11",
            form: .macBook,
            image: "https://cdsassets.apple.com/live/7WUAS350/images/macbook-pro/macbook-pro-late-2012-13in-device.jpg",
            capabilities: [.pro, .usbC],
            models: ["MD212xx/A", "MD213xx/A"],
            colors: .legacySilverMacs,
            cpu: .intel),
        Mac(
            officialName: "MacBook Pro (Retina, 15-inch, Mid 2012)",
            identifiers: ["MacBookPro10,1"],
            introduction: 2012.introductionYear,
            supportId: "112576",
            launchOSVersion: "10.7.4",
            unsupportedOSVersion: "11",
            form: .macBook,
            image: "https://cdsassets.apple.com/live/7WUAS350/images/macbook-pro/macbook-pro-mid-2012-15in-device.jpg",
            capabilities: [.pro, .usbC],
            colors: .legacySilverMacs,
            cpu: .intel),
        Mac(
            officialName: "MacBook Pro (15-inch, Mid 2012)",
            identifiers: ["MacBookPro9,1"],
            introduction: 2012.introductionYear,
            supportId: "112568",
            launchOSVersion: "10.7.3",
            unsupportedOSVersion: "11",
            form: .macBook,
            image: "https://cdsassets.apple.com/live/7WUAS350/images/macbook-pro/macbook-pro-mid-2012-15in-device2.jpg",
            capabilities: [.pro, .usbC],
            models: ["MD103xx/A", "MD104xx/A"],
            colors: .legacySilverMacs,
            cpu: .intel),
        Mac(
            officialName: "MacBook Pro (13-inch, Mid 2012)",
            identifiers: ["MacBookPro9,2"],
            introduction: 2012.introductionYear,
            supportId: "111958",
            launchOSVersion: "10.7.3",
            unsupportedOSVersion: "11",
            form: .macBook,
            image: "https://cdsassets.apple.com/live/7WUAS350/images/macbook-pro/macbook-pro-mid-2012-13in-device.jpg",
            capabilities: [.pro, .usbC],
            models: ["MD101xx/A", "MD102xx/A"],
            colors: .legacySilverMacs,
            cpu: .intel),
        Mac(
            officialName: "MacBook Pro (17-inch, Late 2011)",
            identifiers: ["MacBookPro8,3"],
            introduction: 2011.introductionYear,
            supportId: "112418",
            launchOSVersion: "10.6.6",
            unsupportedOSVersion: "10.14",
            form: .macBook,
            image: "https://cdsassets.apple.com/live/7WUAS350/images/macbook-pro/macbook-pro-late-2011-17in-device.jpg",
            capabilities: [.pro, .usbC],
            models: ["MD311xx/A"],
            colors: .legacySilverMacs,
            cpu: .intel),
        Mac(
            officialName: "MacBook Pro (15-inch, Late 2011)",
            identifiers: ["MacBookPro8,2"],
            introduction: 2011.introductionYear,
            supportId: "112586",
            launchOSVersion: "10.7.2",
            unsupportedOSVersion: "10.14",
            form: .macBook,
            image: "https://cdsassets.apple.com/live/7WUAS350/images/macbook-pro/macbook-pro-late-2011-15in-device.jpg",
            capabilities: [.pro, .usbC],
            models: ["MD322xx/A", "MD318xx/A"],
            colors: .legacySilverMacs,
            cpu: .intel),
        Mac(
            officialName: "MacBook Pro (13-inch, Late 2011)",
            identifiers: ["MacBookPro8,1"],
            introduction: 2011.introductionYear,
            supportId: "111341",
            launchOSVersion: "10.6.6",
            unsupportedOSVersion: "10.14",
            form: .macBook,
            image: "https://cdsassets.apple.com/live/7WUAS350/images/macbook-pro/macbook-pro-late-2011-13in-device.jpg",
            capabilities: [.pro, .usbC],
            models: ["MD314xx/A", "MD313xx/A"],
            colors: .legacySilverMacs,
            cpu: .intel),
        Mac(
            officialName: "MacBook Pro (17-inch, Early 2011)",
            identifiers: ["MacBookPro8,3"],
            introduction: 2011.introductionYear,
            supportId: "112598",
            launchOSVersion: "10.6.6",
            unsupportedOSVersion: "10.14",
            form: .macBook,
            image: "https://cdsassets.apple.com/live/7WUAS350/images/macbook-pro/macbook-pro-early-2011-17in-device.jpg",
            capabilities: [.pro, .usbC],
            models: ["MC725xx/A"],
            colors: .legacySilverMacs,
            cpu: .intel),
        Mac(
            officialName: "MacBook Pro (15-inch, Early 2011)",
            identifiers: ["MacBookPro8,2"],
            introduction: 2011.introductionYear,
            supportId: "112599",
            launchOSVersion: "10.6.6",
            unsupportedOSVersion: "10.14",
            form: .macBook,
            image: "https://cdsassets.apple.com/live/7WUAS350/images/macbook-pro/macbook-pro-early-2011-15in-device.jpg",
            capabilities: [.pro, .usbC],
            models: ["MC723xx/A", "MC721xx/A"],
            colors: .legacySilverMacs,
            cpu: .intel),
        Mac(
            officialName: "MacBook Pro (13-inch, Early 2011)",
            identifiers: ["MacBookPro8,1"],
            introduction: 2011.introductionYear,
            supportId: "112600",
            launchOSVersion: "10.6.6",
            unsupportedOSVersion: "10.14",
            form: .macBook,
            image: "https://cdsassets.apple.com/live/7WUAS350/images/macbook-pro/macbook-pro-early-2011-13in-device.jpg",
            capabilities: [.pro, .usbC],
            models: ["MC724xx/A", "MC700xx/A"],
            colors: .legacySilverMacs,
            cpu: .intel),
        Mac(
            officialName: "MacBook Pro (17-inch, Mid 2010)",
            identifiers: ["MacBookPro6,1"],
            introduction: 2010.introductionYear,
            supportId: "112606",
            launchOSVersion: "10.6.3",
            unsupportedOSVersion: "10.14",
            form: .macBook,
            image: "https://cdsassets.apple.com/live/7WUAS350/images/macbook-pro/macbook-pro-mid-2010-17in-device.jpg",
            capabilities: [.pro, .usbC],
            models: ["MC024xx/A"],
            colors: .legacySilverMacs,
            cpu: .intel),
        Mac(
            officialName: "MacBook Pro (15-inch, Mid 2010)",
            identifiers: ["MacBookPro6,2"],
            introduction: 2010.introductionYear,
            supportId: "112605",
            launchOSVersion: "10.6.3",
            unsupportedOSVersion: "10.14",
            form: .macBook,
            image: "https://cdsassets.apple.com/live/7WUAS350/images/macbook-pro/macbook-pro-mid-2010-15in-device.jpg",
            capabilities: [.pro, .usbC],
            models: ["MC373xx/A", "MC372xx/A", "MC371xx/A"],
            colors: .legacySilverMacs,
            cpu: .intel),
        Mac(
            officialName: "MacBook Pro (13-inch, Mid 2010)",
            identifiers: ["MacBookPro7,1"],
            introduction: 2010.introductionYear,
            supportId: "112604",
            launchOSVersion: "10.6.3",
            unsupportedOSVersion: "10.14",
            form: .macBook,
            image: "https://cdsassets.apple.com/live/7WUAS350/images/macbook-pro/macbook-pro-mid-2010-13in-device.jpg",
            capabilities: [.pro, .usbC],
            models: ["MC375xx/A", "MC374xx/A"],
            colors: .legacySilverMacs,
            cpu: .intel),
        Mac(
            officialName: "MacBook Pro (17-inch, Mid 2009)",
            identifiers: ["MacBookPro5,2"],
            introduction: 2009.introductionYear,
            supportId: "112473",
            launchOSVersion: "10.5.6",
            unsupportedOSVersion: "10.12",
            form: .macBook,
            image: "https://cdsassets.apple.com/live/7WUAS350/images/macbook-pro/macbook-pro-early-mid-2009-17in-device.jpg",
            capabilities: [.pro, .usbC],
            models: ["MC226xx/A"],
            colors: .legacySilverMacs,
            cpu: .intel),
        Mac(
            officialName: "MacBook Pro (15-inch, Mid 2009)",
            identifiers: ["MacBookPro5,3"],
            introduction: 2009.introductionYear,
            supportId: "112624",
            launchOSVersion: "10.5.7",
            unsupportedOSVersion: "10.12",
            form: .macBook,
            image: "https://cdsassets.apple.com/live/7WUAS350/images/macbook-pro/macbook-pro-mid-2009-15in-device.jpg",
            capabilities: [.pro, .usbC],
            models: ["MB985xx/A", "MB986xx/A"],
            colors: .legacySilverMacs,
            cpu: .intel),
        Mac(
            officialName: "MacBook Pro (15-inch, 2.53GHz, Mid 2009)",
            identifiers: ["MacBookPro5,3"],
            introduction: 2009.introductionYear,
            supportId: "112624",
            launchOSVersion: "10.5.7",
            unsupportedOSVersion: "10.12",
            form: .macBook,
            image: "https://cdsassets.apple.com/live/7WUAS350/images/macbook-pro/macbook-pro-mid-2009-15in-device.jpg",
            capabilities: [.pro, .usbC],
            models: ["MC118xx/A"],
            colors: .legacySilverMacs,
            cpu: .intel),
        Mac(
            officialName: "MacBook Pro (13-inch, Mid 2009)",
            identifiers: ["MacBookPro5,5"],
            introduction: 2009.introductionYear,
            supportId: "112474",
            launchOSVersion: "10.5.7",
            unsupportedOSVersion: "10.12",
            form: .macBook,
            image: "https://cdsassets.apple.com/live/7WUAS350/images/macbook-pro/macbook-pro-mid-2009-13in-device.jpg",
            capabilities: [.pro, .usbC],
            models: ["MB991xx/A", "MB990xx/A"],
            colors: .legacySilverMacs,
            cpu: .intel),
        Mac(
            officialName: "MacBook Pro (17-inch, Early 2009)",
            identifiers: ["MacBookPro5,2"],
            introduction: 2009.introductionYear,
            supportId: "112526",
            launchOSVersion: "10.5.6",
            unsupportedOSVersion: "10.12",
            form: .macBook,
            image: "https://cdsassets.apple.com/live/7WUAS350/images/macbook-pro/macbook-pro-early-mid-2009-17in-device.jpg",
            capabilities: [.pro, .usbC],
            models: ["MB604xx/A"],
            colors: .legacySilverMacs,
            cpu: .intel),
        Mac(
            officialName: "MacBook Pro (15-inch, Late 2008)",
            identifiers: ["MacBookPro5,1"],
            introduction: 2008.introductionYear,
            supportId: .unknownSupportId,
            launchOSVersion: "10.5.5",
            unsupportedOSVersion: "10.12",
            form: .macBook,
            image: "https://cdsassets.apple.com/live/7WUAS350/images/macbook-pro/macbook-pro-late-2008-15in-device.jpg",
            capabilities: [.pro, .usbC],
            models: ["MB470xx/A", "MB471xx/A"],
            colors: .legacySilverMacs,
            cpu: .intel),
        Mac(
            officialName: "MacBook Pro (17-inch, Early 2008)",
            identifiers: ["MacBookPro4,1"],
            introduction: 2008.introductionYear,
            supportId: .unknownSupportId,
            launchOSVersion: "10.5.2",
            unsupportedOSVersion: "10.12",
            form: .macBook,
            image: "https://cdsassets.apple.com/live/7WUAS350/images/macbook-pro/macbook-pro-early-2008-17in-device.jpg",
            capabilities: [.pro, .usbC],
            models: ["MB166xx/A"],
            colors: .legacySilverMacs,
            cpu: .intel),
        Mac(
            officialName: "MacBook Pro (15-inch, Early 2008)",
            identifiers: ["MacBookPro4,1"],
            introduction: 2008.introductionYear,
            supportId: .unknownSupportId,
            launchOSVersion: "10.5.2",
            unsupportedOSVersion: "10.12",
            form: .macBook,
            image: "https://cdsassets.apple.com/live/7WUAS350/images/macbook-pro/macbook-pro-early-2008-15in-device.jpg",
            capabilities: [.pro],
            models: ["MB133xx/A", "MB134xx/A"],
            colors: .legacySilverMacs,
            cpu: .intel),

        // MARK: - Mac Studios
        Mac(
            officialName: "Mac Studio (2022) M1 Max", // have to be different from next item or will crash
            identifiers: ["Mac13,1"],
            introduction: 2022.introductionYear,
            supportId: "111900", // have to be different from next item or will crash?? - not sure why since identifiers and officialName are different
            launchOSVersion: "12.3",
            unsupportedOSVersion: nil,
            form: .macStudio,
            image: "https://cdsassets.apple.com/live/7WUAS350/images/mac-studio/mac-studio-2022-m1-max.png",
            capabilities: [.usbC, .thunderbolt, .headphoneJack], // .hdmi, .sdCardSlot, .ethernet, .usbA, no battery
            models: ["MJMV2xx/a"],
            colors: [.silverLight],
            cpu: .m1max),
        Mac(
            officialName: "Mac Studio (2022) M1 Ultra", // have to be different from next item or will crash
            identifiers: ["Mac13,2"],
            introduction: 2022.introductionYear,
            supportId: "111900",
            launchOSVersion: "12.3",
            unsupportedOSVersion: nil,
            form: .macStudio,
            image: "https://cdsassets.apple.com/live/7WUAS350/images/mac-studio/mac-studio-2022-m1-ultra.png",
            capabilities: [.usbC, .thunderbolt, .headphoneJack], // .hdmi, .sdCardSlot, .ethernet, .usbA, no battery
            models: ["MJMW3xx/a"],
            colors: [.silverLight],
            cpu: .m1ultra),
        Mac(
            officialName: "Mac Studio (2023) M2 Max", // have to be different from next item or will crash
            identifiers: ["Mac14,13"],
            introduction: 2023.introductionYear,
            supportId: "111835", // have to be different from next item or will crash? - not sure why since identifiers and officialName are different
            launchOSVersion: "13.4",
            unsupportedOSVersion: nil,
            form: .macStudio,
            image: "https://cdsassets.apple.com/live/7WUAS350/images/mac-studio/mac-studio-2023-m2-max.png",
            capabilities: [.usbC, .thunderbolt, .headphoneJack], // .hdmi, .sdCardSlot, .ethernet, .usbA, no battery
            models: ["MQH73xx/A"],
            colors: [.silverLight],
            cpu: .m2max),
        Mac(
            officialName: "Mac Studio (2023) M2 Ultra", // have to be different from next item or will crash
            identifiers: ["Mac14,14"],
            introduction: 2023.introductionYear,
            supportId: "111835", // have to be different from next item or will crash?? - not sure why since identifiers and officialName are different
            launchOSVersion: "13.4",
            unsupportedOSVersion: nil,
            form: .macStudio,
            image: "https://cdsassets.apple.com/live/7WUAS350/images/mac-studio/mac-studio-2023-m2-ultra.png",
            capabilities: [.usbC, .thunderbolt, .headphoneJack], // .hdmi, .sdCardSlot, .ethernet, .usbA, no battery
            models: ["MQH63xx/A"],
            colors: [.silverLight],
            cpu: .m2ultra),
        Mac(
            officialName: "Mac Studio (2025) M4 Max", // have to be different from next item or will crash
            identifiers: ["Mac16,9"],
            introduction: 2025.introductionYear,
            supportId: "122211",
            launchOSVersion: "15.3.1", // TODO: Check
            unsupportedOSVersion: nil,
            form: .macStudio,
            image: "https://cdsassets.apple.com/live/7WUAS350/images/mac-studio/mac-studio-2025-m4-max.png",
            capabilities: [.usbC, .thunderbolt, .headphoneJack], // .hdmi, .sdCardSlot, .ethernet, .usbA, no battery
            models: ["MU963xx/A"],
            colors: [.silverLight],
            cpu: .m4max),
        Mac(
            officialName: "Mac Studio (2025) M3 Ultra", // have to be different from next item or will crash
            identifiers: ["Mac15,14"],
            introduction: 2025.introductionYear,
            supportId: "122211",
            launchOSVersion: "15.3.1", // TODO: Check
            unsupportedOSVersion: nil,
            form: .macStudio,
            image: "https://cdsassets.apple.com/live/7WUAS350/images/mac-studio/mac-studio-2025-m3-ultra.png",
            capabilities: [.usbC, .thunderbolt, .headphoneJack], // .hdmi, .sdCardSlot, .ethernet, .usbA, no battery
            models: ["MU973xx/A"],
            colors: [.silverLight],
            cpu: .m3ultra),

        // MARK: - Mac minis
        Mac(
            officialName: "Mac mini (2024) M4 Pro", // have to be different from next item or will crash
            identifiers: ["Mac16,11"], // "Mac16,15"
            introduction: 2024.introductionYear,
            supportId: "121555", // have to be different from next item or will crash? - not sure why since identifiers and officialName are different
            launchOSVersion: "15.0",
            unsupportedOSVersion: nil,
            form: .macMini,
            image: "https://cdsassets.apple.com/live/7WUAS350/images/mac-mini/mac-mini-2024.png", // have to be different from next item or will crash? - not sure why since identifiers and officialName are different
            capabilities: [.headphoneJack, .usbC, .thunderbolt],
            models: ["MCX44xx/A", "MCYT4xx/A", "MDAP4xx/A", "MDAQ4xx/A", "MDAY4xx/A", "MU9D3xx/A", "MU9E3xx/A"],
            colors: [.silverLight],
            cpu: .m4pro),
        Mac(
            officialName: "Mac mini (2024) M4",
            identifiers: ["Mac16,10"],
            introduction: 2024.introductionYear,
            supportId: "121555",
            launchOSVersion: "15.0",
            unsupportedOSVersion: nil,
            form: .macMini,
            image: "https://cdsassets.apple.com/live/7WUAS350/images/mac-mini/mac-mini-2024.png",
            capabilities: [.usbC, .thunderbolt],
            colors: [.silverLight],
            cpu: .m4),

        Mac(
            officialName: "Mac mini (2023) M2",
            identifiers: ["Mac14,3"],
            introduction: 2023.introductionYear,
            supportId: "111837", // SP891
            launchOSVersion: "13.2",
            unsupportedOSVersion: nil,
            form: .macMini,
            image: "https://cdsassets.apple.com/live/7WUAS350/images/mac-mini/mac-mini-2023-m2.png",
            capabilities: [.headphoneJack, .usbC, .ethernet, .thunderbolt],
            models: ["MMFJ3xx/A", "MMFK3xx/A"],
            colors: .legacySilverMacs,
            cpu: .m2),
        Mac(
            officialName: "Mac mini (2023) M2 Pro",
            identifiers: ["Mac14,12"],
            introduction: 2023.introductionYear,
            supportId: "111837",
            launchOSVersion: "13.2",
            unsupportedOSVersion: nil,
            form: .macMini,
            image: "https://cdsassets.apple.com/live/7WUAS350/images/mac-mini/mac-mini-2023-m2-pro.png",
            capabilities: [.headphoneJack, .usbC, .ethernet, .thunderbolt],
            models: ["MNH73xx/A"],
            colors: [.solidSilver],
            cpu: .m2pro),
        Mac(
            officialName: "Mac mini (M1, 2020)",
            identifiers: ["Macmini9,1"],
            introduction: 2020.introductionYear,
            supportId: "111894",
            launchOSVersion: "11.0.1",
            unsupportedOSVersion: nil,
            form: .macMini,
            image: "https://cdsassets.apple.com/live/7WUAS350/images/mac-mini/mac-mini-2020-m1.png",
            capabilities: [.usbC, .thunderbolt],
            models: ["MGNR3xx/A", "MGNT3xx/A"],
            colors: [.solidSilver],
            cpu: .m1),
        Mac(
            officialName: "Mac mini (2018)",
            identifiers: ["Macmini8,1"],
            introduction: 2018.introductionYear,
            supportId: "111912",
            launchOSVersion: "10.14",
            unsupportedOSVersion: "26",
            form: .macMini,
            image: "https://cdsassets.apple.com/live/7WUAS350/images/mac-mini/mac-mini-2018.png",
            capabilities: [.usbC, .thunderbolt],
            models: ["MRTR2xx/A", "MRTT2xx/A", "MXNF2xx/A", "MXNG2xx/A"],
            colors: [.macbookSpacegray],
            cpu: .intel),
        Mac(
            officialName: "Mac mini (Late 2014)",
            identifiers: ["Macmini7,1"],
            introduction: 2014.introductionYear,
            supportId: "111931",
            launchOSVersion: "10.10",
            unsupportedOSVersion: "13",
            form: .macMini,
            image: "https://cdsassets.apple.com/live/7WUAS350/images/mac-mini/mac-mini-late-2014.png",
            capabilities: [.usbC, .thunderbolt],
            models: ["MGEM2xx/A", "MGEN2xx/A", "MGEQ2xx/A"],
            colors: .legacySilverMacs,
            cpu: .intel),
        Mac(
            officialName: "Mac mini (Late 2012)",
            identifiers: ["Macmini6,1", "Macmini6,2"],
            introduction: 2012.introductionYear,
            supportId: "111926",
            launchOSVersion: "10.8.1",
            unsupportedOSVersion: "11",
            form: .macMini,
            image: "https://cdsassets.apple.com/live/7WUAS350/images/mac-mini/mac-mini-late-2012.png",
            capabilities: [.usbC, .thunderbolt],
            models: ["MD387xx/A", "MD388xx/A", "MD389xx/A"],
            colors: .legacySilverMacs,
            cpu: .intel),
        Mac(
            officialName: "Mac mini (Mid 2011)",
            identifiers: ["Macmini5,1", "Macmini5,2"],
            introduction: 2011.introductionYear,
            supportId: "112007",
            launchOSVersion: "10.7",
            unsupportedOSVersion: "10.14",
            form: .macMini,
            image: "https://cdsassets.apple.com/live/7WUAS350/images/mac-mini/mac-mini-mid-2011.png",
            capabilities: [.usbC, .thunderbolt],
            models: ["MC815xx/A", "MC816xx/A", "MC936xx/A"],
            colors: .legacySilverMacs,
            cpu: .intel),
        Mac(
            officialName: "Mac mini (Mid 2010)",
            identifiers: ["Macmini4,1"],
            introduction: 2010.introductionYear,
            supportId: "112588",
            launchOSVersion: "10.6.4",
            unsupportedOSVersion: "10.14",
            form: .macMini,
            image: "https://cdsassets.apple.com/live/7WUAS350/images/mac-mini/mac-mini-mid-2010.png",
            capabilities: [.usbC],
            models: ["MC438xx/A", "MC270xx/A"],
            colors: .legacySilverMacs,
            cpu: .intel),
        Mac(
            officialName: "Mac mini (Late 2009)",
            identifiers: ["Macmini3,1"],
            introduction: 2009.introductionYear,
            supportId: "112482",
            launchOSVersion: "10.6",
            unsupportedOSVersion: "10.12",
            form: .macMini,
            image: "https://cdsassets.apple.com/live/7WUAS350/images/mac-mini/mac-mini-late-2009.png",
            capabilities: [.usbC],
            models: ["MC238xx/A", "MC239xx/A", "MC408xx/A"],
            colors: .legacySilverMacs,
            cpu: .intel),
        Mac(
            officialName: "Mac mini (Early 2009)",
            identifiers: ["Macmini3,1"],
            introduction: 2009.introductionYear,
            supportId: "111345",
            launchOSVersion: "10.5",
            unsupportedOSVersion: "10.12", // everymac says last supported is 10.11.6
            form: .macMini,
            image: "https://cdsassets.apple.com/live/7WUAS350/images/mac-mini/mac-mini-early-2009.png",
            capabilities: [.usbC],
            models: ["MB464xx/A", "MB463xx/A"],
            colors: .legacySilverMacs,
            cpu: .intel),
        
        // MARK: - Mac Pros
        Mac(
            officialName: "Mac Pro (2023)",
            identifiers: ["Mac14,8"],
            introduction: 2023.introductionYear,
            supportId: "111343",
            launchOSVersion: "13.4",
            unsupportedOSVersion: nil,
            form: .macProGen3,
            image: "https://cdsassets.apple.com/live/7WUAS350/images/mac-pro/id-mac-pro-2019.jpg",
            capabilities: [.biometrics(.touchID)],
            colors: [.silverLight],
            cpu: .m2ultra),
        Mac(
            officialName: "Mac Pro (Rack, 2023)",
            identifiers: ["Mac14,8"],
            introduction: 2023.introductionYear,
            supportId: "111343",
            launchOSVersion: "13.4",
            unsupportedOSVersion: nil,
            form: .macProGen3,
            image: "https://cdsassets.apple.com/live/7WUAS350/images/mac-pro/id-mac-pro-2019-rack.jpg",
            capabilities: [.biometrics(.touchID)],
            colors: [.silverLight],
            cpu: .m2ultra),
        Mac(
            officialName: "Mac Pro (2019)",
            identifiers: ["MacPro7,1"],
            introduction: 2019.introductionYear,
            supportId: "118461",
            launchOSVersion: "10.15.1",
            unsupportedOSVersion: nil,
            form: .macProGen3,
            image: "https://cdsassets.apple.com/live/7WUAS350/images/mac-pro/id-mac-pro-2019.jpg",
            capabilities: [.biometrics(.touchID)],
            colors: [.silverLight],
            cpu: .intel),
        Mac(
            officialName: "Mac Pro (Rack, 2019)",
            identifiers: ["MacPro7,1"],
            introduction: 2019.introductionYear,
            supportId: "111907",
            launchOSVersion: "10.15.1",
            unsupportedOSVersion: nil,
            form: .macProGen3,
            image: "https://cdsassets.apple.com/live/7WUAS350/images/mac-pro/id-mac-pro-2019-rack.jpg",
            capabilities: [.biometrics(.touchID)],
            colors: [.silverLight],
            cpu: .intel),
        Mac(
            officialName: "Mac Pro (Late 2013)",
            identifiers: ["MacPro6,1"],
            introduction: 2013.introductionYear,
            supportId: "112025",
            launchOSVersion: "10.9.1",
            unsupportedOSVersion: "13",
            form: .macProGen2,
            image: "https://cdsassets.apple.com/live/7WUAS350/images/mac-pro/id-mac-pro-2013.jpg",
            models: ["ME253xx/A", "MD878xx/A"],
            colors: [.black], // shiny jet black
            cpu: .intel),
        Mac(
            officialName: "Mac Pro (Mid 2012)",
            identifiers: ["MacPro5,1"],
            introduction: 2012.introductionYear,
            supportId: "118464",
            launchOSVersion: "10.6.4",
            unsupportedOSVersion: "10.15",
            form: .macProGen1,
            image: "https://cdsassets.apple.com/live/7WUAS350/images/mac-pro/id-mac-pro-2009-2012.jpg",
            models: ["MD770xx/A", "MD771xx/A"],
            colors: .legacySilverMacs,
            cpu: .intel),
        Mac(
            officialName: "Mac Pro Server (Mid 2012)",
            identifiers: ["MacPro5,1"],
            introduction: 2012.introductionYear,
            supportId: "118464",
            launchOSVersion: "10.6.4",
            unsupportedOSVersion: "10.15",
            form: .macProGen1,
            image: "https://cdsassets.apple.com/live/7WUAS350/images/mac-pro/id-mac-pro-2009-2012.jpg",
            models: ["MD772xx/A"],
            colors: .legacySilverMacs,
            cpu: .intel),
        Mac(
            officialName: "Mac Pro (Mid 2010)",
            identifiers: ["MacPro5,1"],
            introduction: 2010.introductionYear,
            supportId: "112578",
            launchOSVersion: "10.6.4",
            unsupportedOSVersion: "10.15",
            form: .macProGen1,
            image: "https://cdsassets.apple.com/live/7WUAS350/images/mac-pro/id-mac-pro-2009-2012.jpg",
            capabilities: [],
            models: ["MC250xx/A", "MC560xx/A", "MC561xx/A"],
            colors: .legacySilverMacs,
            cpu: .intel),
        Mac(
            officialName: "Mac Pro Server (Mid 2010)",
            identifiers: ["MacPro5,1"],
            introduction: 2010.introductionYear,
            supportId: "112578",
            launchOSVersion: "10.6.4",
            unsupportedOSVersion: "10.15",
            form: .macProGen1,
            image: "https://cdsassets.apple.com/live/7WUAS350/images/mac-pro/id-mac-pro-2009-2012.jpg",
            capabilities: [],
            models: ["MC915xx/A"],
            colors: .legacySilverMacs,
            cpu: .intel),
        Mac(
            officialName: "Mac Pro (Early 2009)",
            identifiers: ["MacPro4,1"],
            introduction: 2009.introductionYear,
            supportId: "112590",
            launchOSVersion: "10.5.6",
            unsupportedOSVersion: "10.12",
            form: .macProGen1,
            image: "https://cdsassets.apple.com/live/7WUAS350/images/mac-pro/id-mac-pro-2009-2012.jpg",
            capabilities: [], // FireWire 800, USB-A
            models: ["MB871xx/A", "MB535xx/A"],
            colors: .legacySilverMacs,
            cpu: .intel),
    ]
}
